### ISSUE TITLE
Initial Event Loop Run

### ISSUE THREAD

**Issue by DasLixou** [rust-windowing/winit#3333] opened 2023-12-27 18:22 UTC
I have a value that is taken by a function and is not Clone, and i need to call that function on init together with the event loop window target. Now there is `Event::NewEvents(StartCause::Init)` but that could theoretically be called multiple times so the rust analyzer errors.
Could we have another impl FnOnce as a parameter that is called on the beginning?

**Comment by madsmtm** [comment] 2023-12-27 20:23
This is being worked on, see https://github.com/rust-windowing/winit/pull/3073.

**Comment by DasLixou** [comment] 2023-12-27 20:50
> This is being worked on, see https://github.com/rust-windowing/winit/pull/3073.

Last Update was 4 months ago, any reason this is blocked?

**Comment by madsmtm** [comment] 2023-12-27 21:03
Previously, mostly man-hours and motivation, although also that the desired design wasn't properly fleshed out.

Currently there's talk on Matrix about rewriting certain things in Winit, so that's also somewhat blocking progress here (I know that's a terrible answer, but that is roughly the status quo).

**Comment by madsmtm** [comment] 2023-12-27 21:06
Anyhow, am gonna close this as a duplicate of https://github.com/rust-windowing/winit/issues/2903, let the discussion continue there.

**Closed by madsmtm** 2023-12-27 21:06 UTC
Labels: S - api, C - needs discussion
