### ISSUE TITLE
Add DroppedFile support for Wayland

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#2083] opened 2021-12-03 19:28 UTC
The `DroppedFile` event should be supported on Wayland through the data device, but afaik at this point the feature isn't implemented on Wayland yet.

I suppose the `HoveredFile` and `HoveredFileCancelled` could also be implemented, but I'm mainly concerned with the `DroppedFile` event.

**Comment by kchibisov** [comment] 2021-12-04 10:37
It uses the same protocol and shares objects as clipboard, so winit should also support clipboard to have drag and drop implemented, which is not the case right now...

**Comment by WhyNotHugo** [comment] 2021-12-04 11:31
> so winit should also support clipboard to have drag and drop implemented

Not really. They re-use the same objects because copy-pasting and drag-dropping share a lot of the same concepts, but you can implement the latter without the former.

**Comment by chrisduerr** [comment] 2021-12-04 15:52
> you can implement the latter without the former.

*Can* and *should* aren't necessarily the same here though.

**Comment by kchibisov** [comment] 2022-04-09 18:05
Duplicate of #1881.

**Closed by kchibisov** 2022-04-09 18:05 UTC
Labels: status: help wanted, platform: Wayland
