### ISSUE TITLE
Softbuffer 0.4.3 fail  (Visual 0x78 does not use softbuffer's pixel format and is unsupported)

### ISSUE THREAD

**Issue by lorenko** [rust-windowing/winit#3701] opened 2024-05-21 18:31 UTC
### Description

with softbuffer 0.4.3 I have this error message
need to downgrade to 0.4.0
`cargo update --package softbuffer --precise 0.4.0
`
for window.rs to work

```
winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.25
thread 'main' panicked at examples/window.rs:467:46:
failed to create initial window: PlatformError(Some("Visual 0x78 does not use softbuffer's pixel format and is unsupported"), None)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1034:23
   4: <window::Application as winit::application::ApplicationHandler<window::UserEvent>>::resumed
             at ./examples/window.rs:467:9
   5: winit::platform_impl::platform::x11::EventLoop<T>::single_iteration
             at ./src/platform_impl/linux/x11/mod.rs:522:13
   6: winit::platform_impl::platform::x11::EventLoop<T>::pump_app_events
             at ./src/platform_impl/linux/x11/mod.rs:426:13
   7: winit::platform_impl::platform::x11::EventLoop<T>::run_app_on_demand
             at ./src/platform_impl/linux/x11/mod.rs:392:19
   8: winit::platform_impl::platform::x11::EventLoop<T>::run_app
             at ./src/platform_impl/linux/x11/mod.rs:384:9
   9: winit::platform_impl::platform::EventLoop<T>::run_app
             at ./src/platform_impl/linux/mod.rs:792:56
  10: winit::event_loop::EventLoop<T>::run_app
             at ./src/event_loop.rs:250:9
  11: window::main
             at ./examples/window.rs:64:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

### OS and window mananger

Linux MX 23.3 Libretto

OS: MX x86_64 
Kernel: 6.1.0-21-amd64 
Shell: bash 5.2.15 
Resolution: 3840x2160 
DE: Plasma 5.27.5 
WM: KWin 

### Winit version

0.30.0

**Comment by trozen** [comment] 2024-05-31 12:47
I'm having the same issue on Ubuntu 23.10 on X11 (NVidia drivers):
```
thread 'main' panicked at examples/window.rs:467:46:
failed to create initial window: PlatformError(Some("Visual 0x23 does not use softbuffer's pixel format and is unsupported"), None)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by psychon** [comment] 2024-06-01 14:00
Duplicate of https://github.com/rust-windowing/winit/issues/3646

**Closed** 2024-06-24 00:47 UTC
Labels: B - bug, DS - x11
