### ISSUE TITLE
set_simple_fullscreen content is obscured by "The Notch"

### ISSUE THREAD

**Issue by sfsam** [rust-windowing/winit#3742] opened 2024-06-19 15:16 UTC
### Description

New MacBooks have a camera housing that protrudes into the screen. The `set_simple_fullscreen` method does not seem to take this "feature" of newer laptops into account. Thus, window content is obscured by "The Notch". Apple provides an API for macOS 12+ to address this issue. Use the `safeAreaInsets` property to size content so it won't be obscured:

```
The safe area reflects the unobscured portion of the screen. On some Macs, 
the insets reflect the portion of the screen covered by the camera housing. 
If your app offers a custom full-screen experience, apply the specified insets 
to the screen’s frame rectangle to obtain the area within which it is safe to 
display your content. Content in the safe area is guaranteed to be unobscured.
```

https://developer.apple.com/documentation/appkit/nsscreen/3882821-safeareainsets?language=objc

### macOS version

```shell
macOS 14.5 (23F79)
```

### Winit version

0.30.2

**Comment by daxpedda** [comment] 2024-06-24 15:45
@madsmtm I believe this is a duplicate of https://github.com/rust-windowing/winit/issues/2066.

See https://github.com/rust-windowing/winit/issues/2308 as well.

**Comment by daxpedda** [comment] 2024-08-14 12:33
Closing as a duplicate of #2308.

**Closed by daxpedda** 2024-08-14 12:33 UTC
Labels: B - bug, DS - macos
