### ISSUE TITLE
EventLoop::new should return an error instead of panic when there are no display.

### ISSUE THREAD

**Issue by ogoffart** [rust-windowing/winit#3018] opened 2023-08-08 07:56 UTC
When trying to start any application using winit in an environment that can't connect to the display, the applications panics with this panic:

```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:757:9
```

But instead, the EventLoop::new (and EventLoopBuilder::build) should return an error so that we can handle this situation in the calling code.

### Context

The Slint LSP Server can show a preview.  If there is no display server connected, we should ideally report the error though the LSP protocol so that we display a nice error to the user instead of a cryptic panic message. (Or even using a fallback approach)
Reported in https://github.com/slint-ui/slint/issues/3234

In general in Slint, we try to avoid panicking in this kind of situation, and instead report Error to the calling code so they can report decent error instead of confusing panic messages. (but this is unfortunately not always possible if the underlying libraries panics)

**Comment by kchibisov** [comment] 2023-08-13 19:20
Duplicate of #500.

**Closed by kchibisov** 2023-08-13 19:20 UTC
Labels: S - api
