### ISSUE TITLE
Not possible to send events to winit from a Web Worker

### ISSUE THREAD

**Issue by syrel** [rust-windowing/winit#2592] opened 2022-12-15 17:40 UTC
Hi

There doesn't seem to be a way to wake up an event loop or enqueue events coming from a Web Worker due to winit trying to process events right away:

https://github.com/rust-windowing/winit/blob/8934d2765d042ffced4782eb02ba44704644f30f/src/platform_impl/web/event_loop/runner.rs#L200

The referenced code assumes that events can only be sent from the main thread. What would it take to support this use-case?

Thanks!

**Comment by daxpedda** [comment] 2023-06-02 14:41
Duplicate of https://github.com/rust-windowing/winit/issues/1518.

**Closed by daxpedda** 2023-06-02 14:41 UTC
Labels: S - enhancement, DS - wasm
