### ISSUE TITLE
Winit dropping events on X11

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1442] opened 2020-02-07 19:18 UTC
It seems like there is a problem on X11, where it is possible to send custom user events to the event loop, but they never arrive.

This has been reported downstream in https://github.com/alacritty/alacritty/issues/3083.

The following log should display the problem:

```
[2020-02-07 15:55] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7485, tv_nsec: 858681027 }, requested_resume: None })
[2020-02-07 15:55] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(17))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: (empty) }) }
[2020-02-07 15:55] [INFO] glutin event: MainEventsCleared
[2020-02-07 15:55] [INFO] glutin event: RedrawEventsCleared
[2020-02-07 15:55] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7487, tv_nsec: 2493957 }, requested_resume: None })
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Title("echo [@hellbringer] (15:55:07)"))
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Urgent)
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-07 15:55] [INFO] glutin event: MainEventsCleared
[2020-02-07 15:55] [INFO] glutin event: RedrawEventsCleared
REQUESTING REDRAW DUE TO VISUAL BELL
[2020-02-07 15:55] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7487, tv_nsec: 484097551 }, requested_resume: None })
[2020-02-07 15:55] [INFO] glutin event: MainEventsCleared
[2020-02-07 15:55] [INFO] glutin event: RedrawEventsCleared
REQUESTING REDRAW DUE TO VISUAL BELL
[2020-02-07 15:55] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7487, tv_nsec: 504422468 }, requested_resume: None })
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Title("[haarp@hellbringer]:~ 15:55:07"))
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-07 15:55] [INFO] glutin event: UserEvent(Wakeup)
[2020-02-07 15:55] [INFO] glutin event: MainEventsCleared
[2020-02-07 15:55] [INFO] glutin event: RedrawEventsCleared
REQUESTING REDRAW DUE TO VISUAL BELL
[2020-02-07 15:55] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 7487, tv_nsec: 521909413 }, requested_resume: None })
[2020-02-07 15:55] [INFO] glutin event: MainEventsCleared
[2020-02-07 15:55] [INFO] glutin event: RedrawEventsCleared
REQUESTING REDRAW DUE TO VISUAL BELL
```

Note that every `REQUESTING REDRAW DUE TO VISUAL BELL` corresponds to Alacritty sending a `UserEvent(Wakeup)`.

**Comment by murarth** [comment] 2020-02-07 21:04
I'm unable to reproduce this issue, using alacritty `master` or `v0.4.0`, with the minimal configuration in the alacritty issue.

**Comment by chrisduerr** [comment] 2020-02-07 23:09
So am I. While in the issue it was speculated that it could be an Nvidia specific issue, it seems like that's unlikely since the event is dropped by winit which is unrelated to graphics drivers.

I've requested feedback to check if `request_redraw` works instead of sending a custom user event, but in theory both should hopefully be supported.

**Comment by murarth** [comment] 2020-02-08 00:06
I think this may be a manifestation of issue #1243, which affected applications using `EventLoop::run_return`. The issue was resolved by #1245, which was first published in winit `0.20.0-alpha5`. alacritty 0.4.0 depends on winit `0.20.0-alpha4`.

**Comment by chrisduerr** [comment] 2020-02-08 02:18
It's important to note that Alacritty does not actually ever exit out of `run_return` unless the program is shut down. And this issue was reproduced with Alacritty 0.4.2-dev. So I'd say it's very unlikely that this issue is the same as #1243.

**Comment by murarth** [comment] 2020-02-08 06:32
Okay, my mistake. That particular issue is likely unrelated.

Even so, some changes were made concerning X11's event loop between the last alpha release and the proper 0.20.0 release. I'd be interesting in knowing whether an alacritty user can reproduce this issue on a version of alacritty using a non-alpha winit >= 0.20.0.

**Comment by chrisduerr** [comment] 2020-02-08 12:30
It seems like this can be reproduced with `request_redraw` too. So it's not only a problem with user events.

Assuming the latest master was used, the winit version should also be at least 0.20.0. But maybe @haarp can confirm or deny this just to be 100% certain.

**Comment by chrisduerr** [comment] 2020-02-10 13:54
It seems like this problem was indeed not resolved with >= 0.20.0.

**Comment by kchibisov** [comment] 2020-02-10 14:05
Just to make it a bit more clear, the retest was on v0.21.0, and it still has the same problem.

**Comment by heeen** [comment] 2020-02-17 13:35
I can reproduce it with winit master (e88e8bc)

**Comment by chrisduerr** [comment] 2020-11-04 22:37
The visual bell problems were due to an internal problem in Alacritty. However https://github.com/alacritty/alacritty/issues/824 is still present, but there is no evidence that this is due to UserEvents being swallowed.

**Closed** 2020-11-04 22:37 UTC
Labels: platform: X11, status: needs investigation, type: bug
