### ISSUE TITLE
choose which cursor to grab with set_cursor_grab

### ISSUE THREAD

**Issue by SArpnt** [rust-windowing/winit#3984] opened 2024-11-03 07:19 UTC
### Description

wayland linux supports locking specific mouse cursors, but the current winit api only allows grabbing every cursor at the same time. when other cursors touch the window where one is locked, they end up stuck.

this should be relevant on any platform with multiple lockable cursors, but i wouldn't know which platforms those are or how they behave, i only use sway.

### Relevant platforms

Wayland

**Comment by SArpnt** [comment] 2024-11-03 07:42
looking over things again the same thing should probably be applied to the other set_cursor functions. drag_window and drag_resize_window should only affect the cursor that caused the event if it doesn't already.

maybe instead of moving the cursor via the window there could be a cursor handle type to make these operations easier? i'm not familiar with the various backend limitations, so i wouldn't know if that's impractical.

**Comment by kchibisov** [comment] 2024-11-03 11:07
duplicate of #795

**Closed by kchibisov** 2024-11-03 11:07 UTC
Labels: S - enhancement

**Comment by SArpnt** [comment] 2024-11-03 15:25
that issue is about identifying seats, which is *related*, but i don't see anything about being able to actually do operations like cursor locking on those specific cursors or seats.

**Comment by kchibisov** [comment] 2024-11-03 16:57
multiple cursors are only present in multi-seat setups, so all the functions must be seat aware.
