### ISSUE TITLE
Memorize macOS input source

### ISSUE THREAD

**Issue by august64** [rust-windowing/winit#545] opened 2018-06-02 16:25 UTC
Originally tomaka/glutin#961
Related: jwilm/alacritty#945

cc @kalekseev @zindel

**Comment by kalekseev** [comment] 2018-07-28 05:49
Hi @francesca64, first of all thank you for your great work on that project. The issue is bothering me since I started using alacritty but I have zero experience with os x development and don't know where to start so if you don't mind to instruct me then I might try and implement the patch for that.

**Comment by kalekseev** [comment] 2018-10-18 07:48
hi @overlazy I've just built a fresh alacritty and it works! Not sure where the fix was added, you may try and test glutin example app, if it works then it was fixed outside of alacritty, in my old test the example app had that layout issue.

**Comment by overlazy** [comment] 2018-10-18 12:28
Hi @kalekseev, On my first gif I was using windows created by winit (two left ones). So I proved that this  bug is fixed in winit (alacritty here is just to launch two simple winit apps). I did some research and found that this [commit](https://github.com/tomaka/winit/commit/dec728cfa28547f17c650dd945d5d2b73086f879) fixed it.

I think this issue and all related can be closed.

**Closed as completed** 2018-10-18 18:50 UTC
Labels: S - enhancement, H - help wanted, DS - appkit, D - easy, P - normal
