### ISSUE TITLE
Feature request: Let me opt out of web_sys preventDefaults on a per-event basis

### ISSUE THREAD

**Issue by mcclure** [rust-windowing/winit#3797] opened 2024-07-18 01:38 UTC
### Description

I have a web app: https://data.runhello.com/j/wgpu/special/winit-swallow/
That URL is https://github.com/mcclure/webgpu-tutorial-rs/ commit [a8fa378](https://github.com/mcclure/webgpu-tutorial-rs/commit/a8fa37895a22c059788181fd4bae5af5c8f28516).
It is built with Rust + Trunk + winit + webgpu (so it will only work on Chrome or possibly Firefox Nightly).

It has a problem, which is that it swallows right clicks. So if I or a user want to look at the Chrome Inspector, they can't just right click the way they're used to.
I find the documentation explains that winit by default calls [`preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) on every event; and if I add `window.set_prevent_default(false);` to line 979, right after initializing the window, then as documented winit will not do this, pass on the events, and right click works.

But, I do not want *all* events preventDefaulted! For example I don't want the scrollwheel to trigger, and I plan to add special behaviors for click-and-drag. There doesn't currently seem to be a way to request preventDefault for *some* events but not *all*.

So, here is my feature request: add to either `Event<T>` or `ActiveEventLoop` a function named like `prevent_default_current(p: bool)` which, if calls, overrides the `set_prevent_default` for the current event. That way I could default to preventing default, but `prevent_default_current(false)` on right-clicks *specifically*, and that way get the behavior I want in all cases with little hassle.

### Relevant platforms

Web

**Comment by daxpedda** [comment] 2024-07-18 08:24
This is a duplicate of https://github.com/rust-windowing/winit/issues/2831. While we concluded there that it might not be needed to do fine-grained filtering because the only relevant use case is the clipboard, allow the developer console specifically is a use case that might change this outlook.

Note that you can use `WindowAttributes::with_prevent_default()` to do this before creating the window.

**Closed by daxpedda** 2024-07-18 08:24 UTC
Labels: S - enhancement
