### ISSUE TITLE
Expose ScanCode to VirtualKeyCode mapping

### ISSUE THREAD

**Issue by NotAFile** [rust-windowing/winit#2436] opened 2022-08-20 15:51 UTC
In applications that care more about the position of a key than it's function, one is supposed to use a `ScanCode`. However this creates an UI issue when asking the user to press a certain button, if one only knows it's scan code.

The best solution to my knowledge is to pass the scan code through the OS keyboard mapping as if it was a key press to determine the name of the key in that location. However it seems that this currently happens very deep within the platform implementations and is not exposed by `winit`. (e.g. [here in very deep in sctk](https://github.com/Smithay/client-toolkit/blob/93f3f0eeef27ac36873cbc084997b25397505d5e/src/seat/keyboard/mod.rs#L519)). It would be useful to expose this in a cross-platform way, allowing users to map a `ScanCode` to a `VirtualKeyCode` for display in the application.

There have been a lot of discussions about revamping keyboard input that might be relevant (#753, #1806), however I have not seen any issues for this specific functionality yet.

**Comment by kchibisov** [comment] 2023-05-28 17:38
Duplicate of #2678.

Will hopefully be a part of next release.

**Closed by kchibisov** 2023-05-28 17:38 UTC
Labels: S - enhancement, S - api
