### ISSUE TITLE
Custom cursor icons

### ISSUE THREAD

**Issue by valaphee** [rust-windowing/winit#3005] opened 2023-08-04 22:33 UTC
At the moment there is no way to use custom cursor icons (except doing it manually).

All major platforms should support custom cursors even on web.

Loading cursor icons would work the same way as other icons on Windows (LoadImageW), but would require a new method in Window or not using "cursor_icon" and adding a new variant "Custom" to CursorIcon.

**Comment by madsmtm** [comment] 2023-08-05 20:05
Three open PRs on this:
- https://github.com/rust-windowing/winit/pull/1617
- https://github.com/rust-windowing/winit/pull/2117
- https://github.com/rust-windowing/winit/pull/2833

Biggest problem is how to design the desired API for this.

**Comment by kchibisov** [comment] 2023-08-05 20:11
I guess we could do something like 

```
pub enum CursorIcon {
    Named(CursorIcon), // from crate
    Raw(Buffer),
}
```

The issue is that on Wayland you'd need a scaling, but we can accept physical and say that we'll scale based on display resolution?

**Comment by valaphee** [comment] 2023-08-22 14:48
What was the reason why CursorIcon resides in its own crate? I found this pr https://github.com/rust-windowing/winit/commit/bd9cc2a9da7de62bf2cdd5d220f8c3635c3d82cc but I don't think its really worth being in its own crate.

**Comment by kchibisov** [comment] 2023-08-22 15:11
@valaphee it's used by multiple crates(not only winit) and just encodes w3c icons

**Comment by Friz64** [comment] 2023-12-16 21:14
#3218 has been merged 🎉

**Closed** 2023-12-17 02:08 UTC
Labels: S - api, C - needs discussion
