### ISSUE TITLE
macos simple fullscreen on macbook pro with notch

### ISSUE THREAD

**Issue by dannydulai** [rust-windowing/winit#2066] opened 2021-11-17 20:06 UTC
What's the proper way to handle the notch in simple fullscreen mode?

I can think of 3 different types of apps:

1) apps that want to use the area to the sides of the notch
2) apps that don't want to use the area to the sides of the notch and prefer to just have the simple fullscreen window sit below the notch, and have...
2a) the area above the window filled by black or some other color.
2b) the area to the sides of the notch should continue to show the titlebar.

Is this something apps should handle or maybe glutin can abstract that away?

**Comment by maroider** [comment] 2021-11-17 21:03
I think there's definitely a need to expand winit's API to support querying geometry of screens which aren't perfect rectangles.

It would, however, be entirely up to applications to support such screens, so we can't solve your issue with Alacritty. If someone explicitly decides to only support monitors that are perfect rectangles, then that's what's supported.

**Comment by dannydulai** [comment] 2021-11-17 23:08
Yes of course. I've already moved away from alacritty, so I'm in no rush.

The only reason I didn't mention alacrity here is because I think that the future of MacBooks looks "notchy". I'm sure this will come up soon enough outside the scope of alacritty. It's always good to get ideas flowing before a knee-jerk API is created.

**Comment by madsmtm** [comment] 2022-01-10 21:24
Apple calls this concept "safe area", see [their documentation](https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area?language=objc) and [UI guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/#layout-guides-and-safe-areas).

**Comment by daxpedda** [comment] 2024-08-14 12:33
Closing as a duplicate of #2066.

**Closed by daxpedda** 2024-08-14 12:33 UTC
Labels: F - question, DS - macos
