### ISSUE TITLE
Mouse Events show released wrong

### ISSUE THREAD

**Issue by Night-Hunter-NF** [rust-windowing/winit#2728] opened 2023-03-10 04:47 UTC
## Bug
When pressing mouse button 4 or Other(32) down it registers fine but  on release it is show as Other(0)
same for mouse button 5
os is windows

![image](https://user-images.githubusercontent.com/66358962/224225725-1a522a8c-a9de-4e64-84c0-8714ba7832af.png)

**Comment by msiglreith** [comment] 2023-03-12 16:41
Not able to reproduce on `master`. This has been fixed in 0.28 (https://github.com/rust-windowing/winit/pull/2565)

**Closed by msiglreith** 2023-03-12 16:41 UTC
Labels: B - bug, DS - windows
