### ISSUE TITLE
Is Windows 7 supported

### ISSUE THREAD

**Issue by filnet** [rust-windowing/winit#1425] opened 2020-01-30 16:17 UTC
Hi,

Small test app that works on Windows 10 gives an error when compiled and started on Windows 7.

The error is about a missing AdjustWindowRectExForDpi procedure  in USER32.dll.

**Comment by Vengarioth** [comment] 2020-01-30 20:43
I just ran into the same issue when sending a build to friends to test. This call was introduced in windows 10 and is not available to windows 7 or 8.

reproduction is just creating a regular window on these platforms. 

i will dig some more and see if there are more calls that depend on windows 10.

**Comment by Vengarioth** [comment] 2020-01-30 20:46
As this happens on windows 8 as well, which still has support until 2023, it would be cool to have a fallback. i can work on this if desired.

**Comment by kchibisov** [comment] 2020-01-30 20:48
Could you try the latest winit master? It should be fixed by #1398

**Comment by Vengarioth** [comment] 2020-01-30 21:24
Can confirm current master works on 

- [x] Windows 7 Desktop
- [x] Windows 8 Desktop
- [x] Windows 10 Desktop

thanks for the hint!

**Comment by goddessfreya** [comment] 2020-01-30 23:55
Dupe: https://github.com/rust-windowing/winit/issues/1386

**Closed by goddessfreya** 2020-01-30 23:55 UTC
Labels: platform: Windows, status: duplicate, type: bug

**Comment by filnet** [comment] 2020-01-31 09:46
I reproduce the issue on master when running the examples.

```
# cargo run --example timer
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target\debug\examples\timer.exe`
error: process didn't exit successfully: `target\debug\examples\timer.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

**Comment by filnet** [comment] 2020-01-31 10:39
My mistake: was using a slate clone of master.
Works fine now...
