### ISSUE TITLE
no window displayed on gnome wayland

### ISSUE THREAD

**Issue by cbanu** [rust-windowing/winit#1692] opened 2020-08-31 16:21 UTC
I've tried the basic example in `window.rs` on an up-to-date Fedora 32 system running GNOME Wayland.
The application seems to be running, a few events get logged to the console, but there's no window displayed. The only thing I found was that when switching windows via Alt-Tab, I see the "A fantastic window!" entry, but I cannot see the window itself or switch to it.

I've tested against winit 0.22.2 on Fedora 32 (Workstation Edition), GNOME version 3.36.5 with Wayland.

Using the workaround in issue #305 works, however I'm looking at running it against the Wayland backend.

Please let me know if you need more information.

**Comment by kchibisov** [comment] 2020-08-31 16:25
It's a known problem you need to draw something into window on Wayland to make it show. try https://github.com/rust-windowing/glutin/tree/master/glutin examples, since they draw something.

**Comment by kchibisov** [comment] 2020-08-31 16:27
duplicate of https://github.com/rust-windowing/winit/issues/776

**Closed by kchibisov** 2020-08-31 16:27 UTC
