### ISSUE TITLE
[Wayland] usage with WLR layer shell

### ISSUE THREAD

**Issue by Anakael** [rust-windowing/winit#2142] opened 2022-01-09 19:58 UTC
Winit version: 0.26.1

I want to use `surface`, created by `winit` to create layer shell surface by `sctk`.
But following code produce sigsegv:
```rust
let event_loop = EventLoop::new();
let window = WindowBuilder::new().build(&event_loop).unwrap();
let surface = window.wayland_surface().unwrap() as *mut WlSurface;
let surface = unsafe { surface.as_ref() }.unwrap();
let layer_surface = layer_shell.get_layer_surface(
    &surface,
    Some(output),
    zwlr_layer_shell_v1::Layer::Top,
    "example".to_owned(),
);

/// Configure layer surface ...

let next_render_event = Rc::new(Cell::new(None::<RenderEvent>));
let next_render_event_handle = Rc::clone(&next_render_event);
layer_surface.quick_assign(move |layer_surface, event, _| {
match (event, next_render_event_handle.get()) {
        (zwlr_layer_surface_v1::Event::Closed, _) => {
             next_render_event_handle.set(Some(RenderEvent::Closed));
          }
          (
              zwlr_layer_surface_v1::Event::Configure {
                  serial,
                  width,
                  height,
              },
              next,
          ) if next != Some(RenderEvent::Closed) => {
              layer_surface.ack_configure(serial);
              next_render_event_handle.set(Some(RenderEvent::Configure { width, height }));
          }
          (_, _) => {}
      }
 });

surface.commit(); // sigsegv here

event_loop.run(move |event, _, control_flow| {
     *control_flow = ControlFlow::Wait;
      match event {
          Event::WindowEvent {
              event: WindowEvent::CloseRequested,
              window_id,
          } if window_id == window.id() => *control_flow = ControlFlow::Exit,
          _ => (),
      }
});
```
Also, if omit layer shell here at all and call `commit` on `surface` noting changes.

I think it somehow related with `Display`, because next code also produce sigsegv:
```rust
let winit_display = window.wayland_display().unwrap() as *const Display;
let winit_display = unsafe { winit_display.as_ref() }.unwrap();
let id = winit_display.id(); // Id = 0
let is_alive = winit_display.is_alive(); // false
let error = winit_display.protocol_error(); // sigsegv
let fd = winit_display.get_connection_fd(); // sigsegv
```
So, what am I doing wrong and how I can window `Display` and `surface`?

**Comment by Anakael** [comment] 2022-01-10 01:44
Also, I've noticed that there is no created window in sway tree (for the same example), but `toplevel` is created (can be found in output with `WAYLAND_DEBUG=1`).

**Comment by twitchyliquid64** [comment] 2022-01-10 20:43
Funnily enough I'm trying to get this working too!

I don't precisely know your problem, but I'm not sure you're getting the display/surface objects correctly. This works for me:

```rust
    let display = unsafe {
        Display::from_external_display(win.wayland_display().unwrap() as *mut _)
    };
    let surface: WlSurface = unsafe {
        Proxy::<WlSurface>::from_c_ptr(win.wayland_surface().unwrap() as *mut wl_proxy).into()
    };
```

I'm stuck on something else (Im trying to use `glutin` but the issue is that buffers are setup before the window/surface is provided back to me, which is a protocol error when trying to set the surface as a layer_surface), but let me know how you go!

**Comment by kchibisov** [comment] 2022-01-10 20:50
You can't use the surface created by winit for layer-shell since it has role assigned to it. Using winit here isn't an option and using layer surface inside winit also isn't really an option, since layer-shell isn't how default desktop applications should be used.

If you want to use layer-shell, I'd suggest to use smithay/client-toolkit instead.

**Closed by kchibisov** 2022-01-10 20:50 UTC
Labels: platform: Wayland
