### ISSUE TITLE
Automatic theme is not working with run_return

### ISSUE THREAD

**Issue by declantsien** [rust-windowing/winit#2623] opened 2023-01-09 16:41 UTC
* What happens
I am running `cargo run --example window_run_return` on macOS. When toggling dark/light using macOS preference panel, nothing is happening to winit window. As it shows in the [video](https://i.imgur.com/JtkozFU.mp4).

* What should happen
I assumed that automatic theme is supported with `run_return`, so I expected that winit window should reflect the system theme preference.

* How to reproduce the issue
[`window_run_return.rs`](https://github.com/rust-windowing/winit/blob/master/examples/window_run_return.rs) in the examples directory can be used. I am testing at 4b22ca8dafdbc5b17a32d489958b8f37eb1372de from master branch.

**Comment by madsmtm** [comment] 2023-01-21 17:38
I expect that you've tested it with the other examples, and that it works there?

The relevant code for the feature is in the following two snippets:

https://github.com/rust-windowing/winit/blob/d448d3e14fba4a0be09c9e7e383d9a6e605fe6aa/src/platform_impl/macos/window_delegate.rs#L73-L85

https://github.com/rust-windowing/winit/blob/d448d3e14fba4a0be09c9e7e383d9a6e605fe6aa/src/platform_impl/macos/window_delegate.rs#L368-L394

I suspect it could both be caused by `NSDistributedNotificationCenter` not triggering the event, or `performSelectorOnMainThread:` not getting a chance to do so.
Could you check if the `"Triggered effectiveAppearanceDidChange:"` TRACE is output?

---

In general, `run_return` is ill-tested on macOS, so I'd advise you avoid it if you can.

**Comment by declantsien** [comment] 2023-01-22 04:15
Mads Marquart ***@***.***> writes:

> I expect that you've tested it with the other examples, and that it
> works there?

Yeah, I tested last time. This only happens when using `run_return`

> I suspect it could both be caused by `NSDistributedNotificationCenter` not triggering the event, or `performSelectorOnMainThread:` not getting a chance to do so.
> Could you check if the `"Triggered effectiveAppearanceDidChange:"` TRACE is output?
>
I didn't see `Triggered effectiveAppearanceDidChange:`. Here is an
output of `cargo run --example window_run_return > /tmp/log`

TRACE [winit::platform_impl::platform::window] Triggered `WinitWindow::new`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Triggered `frameDidChange:`
TRACE [winit::platform_impl::platform::view] Completed `frameDidChange:`
TRACE [winit::platform_impl::platform::view] Triggered `viewDidMoveToWindow`
TRACE [winit::platform_impl::platform::view] Completed `viewDidMoveToWindow`
TRACE [winit::platform_impl::platform::window] Locked shared state in `WinitWindow::new`
TRACE [winit::platform_impl::platform::window] Unlocked shared state in `WinitWindow::new`
TRACE [winit::platform_impl::platform::window] Locked shared state in `set_fullscreen`
TRACE [winit::platform_impl::platform::window] Unlocked shared state in `set_fullscreen`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeMainWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeMainWindow`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::view] Triggered `acceptsFirstResponder`
TRACE [winit::platform_impl::platform::view] Completed `acceptsFirstResponder`
TRACE [winit::platform_impl::platform::view] Triggered `acceptsFirstResponder`
TRACE [winit::platform_impl::platform::view] Completed `acceptsFirstResponder`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `WinitWindow::new`
TRACE [winit::platform_impl::platform::view] Triggered `resetCursorRects`
TRACE [winit::platform_impl::platform::view] Completed `resetCursorRects`
TRACE [winit::platform_impl::platform::view] Triggered `drawRect:`
TRACE [winit::platform_impl::platform::view] Completed `drawRect:`
TRACE [winit::platform_impl::platform::app_delegate] Triggered `applicationDidFinishLaunching:`
TRACE [winit::platform_impl::platform::app_state] Activating visible window
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeMainWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeMainWindow`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::app_delegate] Completed `applicationDidFinishLaunching:`
Resized(PhysicalSize { width: 1600, height: 1200 })
rendering
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowDidBecomeKey:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowDidBecomeKey:`
TRACE [winit::platform_impl::platform::view] Triggered `mouseEntered:`
TRACE [winit::platform_impl::platform::view] Completed `mouseEntered:`
TRACE [winit::platform_impl::platform::view] Triggered `resetCursorRects`
TRACE [winit::platform_impl::platform::view] Completed `resetCursorRects`
Focused(true)
CursorEntered { device_id: DeviceId(DeviceId) }
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::view] Triggered `flagsChanged:`
TRACE [winit::platform_impl::platform::view] Completed `flagsChanged:`
KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 54, state: Pressed, virtual_keycode: Some(RWin), modifiers: LOGO }, is_synthetic: false }
ModifiersChanged(LOGO)
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::view] Triggered `mouseExited:`
TRACE [winit::platform_impl::platform::view] Completed `mouseExited:`
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowDidResignKey:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowDidResignKey:`
CursorLeft { device_id: DeviceId(DeviceId) }
ModifiersChanged((empty))
Focused(false)
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::view] Triggered `flagsChanged:`
TRACE [winit::platform_impl::platform::view] Completed `flagsChanged:`
ModifiersChanged((empty))
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowDidBecomeKey:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowDidBecomeKey:`
TRACE [winit::platform_impl::platform::view] Triggered `mouseEntered:`
TRACE [winit::platform_impl::platform::view] Completed `mouseEntered:`
Focused(true)
CursorEntered { device_id: DeviceId(DeviceId) }
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowDidResignKey:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowDidResignKey:`
Focused(false)
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 631.019287109375, y: 1034.947509765625 }, modifiers: (empty) }
rendering
CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 631.019287109375, y: 1014.5146484375 }, modifiers: (empty) }
rendering
CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 637.2000732421875, y: 954.2193603515625 }, modifiers: (empty) }
rendering
CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 644.615478515625, y: 861.0992431640625 }, modifiers: (empty) }
rendering
TRACE [winit::platform_impl::platform::view] Triggered `mouseExited:`
TRACE [winit::platform_impl::platform::view] Completed `mouseExited:`
CursorLeft { device_id: DeviceId(DeviceId) }
CursorMoved { device_id: DeviceId(DeviceId), position: PhysicalPosition { x: 659.6759033203125, y: 668.080322265625 }, modifiers: (empty) }
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::window] Triggered `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window] Completed `canBecomeKeyWindow`
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowDidBecomeKey:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowDidBecomeKey:`
Focused(true)
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
rendering
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowShouldClose:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowShouldClose:`
CloseRequested
rendering
TRACE [winit::platform_impl::platform::window] Locked shared state in `fullscreen`
TRACE [winit::platform_impl::platform::window] Unlocked shared state in `fullscreen`
TRACE [winit::platform_impl::platform::window_delegate] Triggered `windowWillClose:`
TRACE [winit::platform_impl::platform::window_delegate] Completed `windowWillClose:`


> In general, `run_return` is ill-tested on macOS, so I'd advise you avoid it if you can.
>

Got it. I was only experimenting with winit as the cross-platform window solution for Emacs.
[Emacs macOS NS port](https://github.com/emacs-mirror/emacs/blob/master/src/nsterm.m#L4720) is using very similar paradigm as winit run_return.

**Comment by madsmtm** [comment] 2024-06-24 12:46
I suspect this is fixed by https://github.com/rust-windowing/winit/pull/3736, feel free to reopen if not!

**Closed by madsmtm** 2024-06-24 12:46 UTC
Labels: B - bug, DS - macos
