### ISSUE TITLE
`with_maximized` does not work on X11 

### ISSUE THREAD

**Issue by SamRodri** [rust-windowing/winit#3719] opened 2024-06-06 02:09 UTC
### Description

To reproduce, create a window using `with_maximized` or `set_maximized(true)` just after creating the window:

```rust
use winit::application::ApplicationHandler;
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, EventLoop};
use winit::window::{Window, WindowId};

#[derive(Default)]
struct App {
    window: Option<Window>,
}

impl ApplicationHandler for App {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        let w = Window::default_attributes().with_maximized(true);
        let w = event_loop.create_window(w).unwrap();
        // w.set_maximized(true);
        self.window = Some(w);
    }

    fn window_event(&mut self, event_loop: &ActiveEventLoop, _id: WindowId, event: WindowEvent) {
        match event {
            WindowEvent::CloseRequested => {
                event_loop.exit();
            },
            WindowEvent::RedrawRequested => {},
            _ => (),
        }
    }
}

fn main() {
    let event_loop = EventLoop::new().unwrap();
    let mut app = App::default();
    event_loop.run_app(&mut app).unwrap();
}

```

The window opens in the "normal" size, if you drag it it briefly resizes to the maximized size and back.

### OS and window mananger

Ubuntu 24.04 LTS, GNOME Shell (default)

### Winit version

0.30.0 and master

**Comment by notgull** [comment] 2024-06-06 03:25
Duplicate of #2360

**Closed by notgull** 2024-06-06 03:25 UTC
Labels: B - bug, DS - x11
