### ISSUE TITLE
I can't figure out the event loop and nothing should be further from the case.

### ISSUE THREAD

**Issue by cheako** [rust-windowing/winit#1054] opened 2019-07-21 06:35 UTC
There should be no mistake in the description of the event loop that's implemented multiple times and will likely be tested on one time but run across many. 

Looks like entire sections are incomplete.

Edit: https://github.com/rust-windowing/winit/issues/459#issuecomment-513513875

**Comment by cheako** [comment] 2019-07-21 13:47
I guess I did figure it out, though I'm not sure how.

I'm working on: https://gitlab.com/cheako/hazel based loosely on https://thecherno.com/engine
Currently the example opens a Window on Linux.

I built my own Vulkan wrapper for this and other projects: https://crates.io/crates/ash-tray

**Comment by cheako** [comment] 2019-07-22 07:56
Sorry, I posted that reply to the wrong issue.  The documentation is still incomplete.

**Comment by felixrabe** [comment] 2019-07-22 10:14
@cheako You can delete the comments to avoid confusing the next person reading this issue.

**Comment by Osspial** [comment] 2019-07-23 04:55
Got any specific feedback points? It's hard to address your issues when you only give a vague problem, and the solution you link doesn't solve the problem you seem to be having in this issue.

Also, does the improved documentation in #1032 solve any of the clarity issues you've brought up?

**Comment by cheako** [comment] 2019-07-23 18:47
#1032 is a good start, it is however impossible to know now if I know enough of what I don't know.

**Comment by cheako** [comment] 2019-07-24 09:36
I thought to look at some of the examples, though if that's a requirement then the relevant examples need to be linked.

This example is of how to use match and not much more.
https://github.com/rust-windowing/winit/blob/master/examples/request_redraw.rs

**Comment by Osspial** [comment] 2019-07-25 19:18
@cheako If you find the examples or documentation unsatisfactory, please go ahead and open a PR that improves them! I'll fully admit that that particular example isn't great, but from the sound of things you've got ideas for how to improve it, and the best way to show off those ideas is to just go ahead and implement them.

**Comment by cheako** [comment] 2019-07-26 06:00
I don't know what I don't know.

**Comment by cheako** [comment] 2019-07-27 06:11
For X11_alpha2 the first event is EventsCleared, not StartCause::Init?

https://gitlab.com/cheako/hazel/blob/afce20a2bd0a1093ed3630f6916445e003e6ee5e/examples/sandbox.rs#L117
Jul 27 01:05:18.318 TRCE Init Event: EventsCleared

**Comment by ZeGentzy** [comment] 2019-07-27 07:04
We do not expose any event known as `StartCause::Init`

**Comment by cheako** [comment] 2019-07-30 19:15
@ZeGentzy
https://docs.rs/winit/0.20.0-alpha2/winit/event/enum.StartCause.html#variant.Init

**Comment by ZeGentzy** [comment] 2019-07-30 19:45
@murarth Can you reproduce an `EventsCleared` event being generated before the `NewEvents`?

**Comment by murarth** [comment] 2019-07-30 20:02
@ZeGentzy: Unable to reproduce and I don't see how that could possibly happen. The first thing `EventLoop::run_return` does, before entering the main `loop`, is unconditionally call the callback with `NewEvents(StartCause::Init)`: https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/x11/mod.rs#L251-L255

**Comment by Osspial** [comment] 2019-07-30 20:16
@cheako

> I don't know what I don't know.

I'll point out that you've brought up [multiple](https://github.com/rust-windowing/winit/issues/1054#issuecomment-514558178) [specific](https://github.com/rust-windowing/winit/issues/1055#issuecomment-513546874) documentation problems that have been an impedance to your understanding of our API. Given that context, this comment makes it seem like you're more interested in complaining about our problems than you are with actually fixing them. That may or may not be the case (I'm hoping it's not!), but it's the image you're presenting and it's impossible for me to ignore.

------

The GitLab link you've provided is broken, and I'm unable to reproduce your issue on master. Could you open a new issue with a relatively compact test case that reproduced it? I'll say that, skimming through the X11 source, the issue you describe *should* be impossible. @murarth posted a good explanation why.

As a side note, since I don't know if you're doing this on purpose - it seems like a lot of the comments you've been making have consistently been [off]-[topic], [unclear], or [dismissive]. That, combined with your stream-of-consciousness style of writing, has made it frustrating to understand your complaints and work with you to solve the issues you've been describing. Please work on addressing those issues. I'd suggest that, after you write your comments, you wait a bit and read over them before posting them, so you can make sure you're coherently and respectfully communicating your intent.

[off]: https://github.com/rust-windowing/winit/issues/1060#issuecomment-515010992
[topic]: https://github.com/rust-windowing/winit/issues/1054#issuecomment-515656039
[unclear]: https://github.com/rust-windowing/winit/issues/1055#issuecomment-513545749
[dismissive]: https://github.com/rust-windowing/winit/issues/1054#issuecomment-515320802

**Comment by ZeGentzy** [comment] 2019-07-30 20:54
> @ZeGentzy: Unable to reproduce and I don't see how that could possibly happen. The first thing `EventLoop::run_return` does, before entering the main `loop`, is unconditionally call the callback with `NewEvents(StartCause::Init)`: https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/x11/mod.rs#L251-L255

Yeah, that's what I was thinking too, @murarth... maybe it's the weirdest heisenbug ever (not to give nightmares or anything :D)?

Anyways- given that this issue has strayed far off from it's original, albeit vague, purpose, I'm closing it. In the future, please provide [specific feedback points, instead of musings on ill-defined "problems".](https://github.com/rust-windowing/winit/issues/1054#issuecomment-514053702)

**Closed by ZeGentzy** 2019-07-30 20:54 UTC
Labels: type: api, type: question
