### ISSUE TITLE
Better ways of initializing an ApplicationHandler

### ISSUE THREAD

**Issue by Astralchroma** [rust-windowing/winit#3808] opened 2024-07-22 04:57 UTC
### Description

The `ApplicationHandler` API presents a problem for any application where a window is required before much can be done as you can't create a window until the first event, by which time you will have already created the struct to represent your application. This means you now have to use `Option<T>` to handle the possibility of no window at some point. The most sane way I have found to do this is to create my own separate application struct, which is stored as an `Option<T>` in the `ApplicationHandler` implementation and simply pass through all the events. This is somewhat messy, and not ideal.

As a solution, I would suggest changing how an event loop is started, the best way I can think of acomplishing this would be to introduce a new `ApplicationHandler::init` method, a rough overview of the idea is as follows:
```rs
struct Application {
	window: Window
}

impl ApplicationHandler<()> for Application {
	type PassedData = String;

	// The addition of PassedData is to make it convenient to pass anything created before the event loop, any API wouldn't necessarily need this, but it would be a useful thing to have.
	fn init(event_loop: &ActiveEventLoop, passed_data: PassedData) -> Self {
		println!("{passed_data}");
		Self {
			window: event_loop.create_window(Window::default_attributes()).unwrap(),
		}
	}
	
	// *All other functions would be same as they are currently*
}

fn main() {
	EventLoop::new()
		.unwrap()
		.run_app::<Application>(String::from("Hello World!"))
		.unwrap();
}
```

**Comment by daxpedda** [comment] 2024-07-22 08:59
Agreed, this could be improved.
I believe this is a duplicate of https://github.com/rust-windowing/winit/issues/2903.

**Closed by daxpedda** 2024-07-22 08:59 UTC
Labels: S - enhancement
