### ISSUE TITLE
Update to Rust 2018 Edition

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/winit#912] opened 2019-06-13 05:33 UTC
See #612, but in issue form.

**Comment by crlf0710** [comment] 2019-06-18 03:36
One thing that previously mentioned but not yet done is migrating to 2018 module structure.

Tried to do the migration locally and filed https://github.com/rust-lang/rust/issues/61924 .

**Comment by felixrabe** [comment] 2019-06-18 21:26
^ The issue created by @crlf0710 was marked as a duplicate of rust-lang/rust#59345.

**Comment by murarth** [comment] 2019-12-05 21:21
Closed by #924

**Closed by murarth** 2019-12-05 21:21 UTC
Labels: type: api, type: enhancement
