### ISSUE TITLE
Creating EventLoop multiple times is not supported.

### ISSUE THREAD

**Issue by andrewbaxter** [rust-windowing/winit#2885] opened 2023-06-17 11:00 UTC
> This restriction isn't strictly necessary on all platforms, but is imposed to eliminate any nasty surprises when porting to platforms that require it.

Porting isn't always necessary, and restarting the event loop allows developers to avoid having to serialize and deserialize state and manage subprocesses and binary paths.

Using a platform-specific library other than winit isn't a great option either, even if there is one using it would mean throwing away the entire ecosystem built on winit.

**Comment by rib** [comment] 2023-06-22 09:05
I think this can be considered a duplicate of https://github.com/rust-windowing/winit/issues/2431

The pump_events branch adds a `run_ondemand` API that allows the event loop to be run, then exit and then be re-run again: https://github.com/rust-windowing/winit/pull/2767

**Comment by daxpedda** [comment] 2023-06-22 10:59
I agree.

Closing in favor of #2431.

**Closed by daxpedda** 2023-06-22 10:59 UTC
Labels: S - enhancement
