### ISSUE TITLE
Windows spinning cursor on startup

### ISSUE THREAD

**Issue by kobutri** [rust-windowing/winit#1682] opened 2020-08-26 14:51 UTC
Try  running the hello-triangle example in release mode on Windows to reproduce.

Not only is the initial startup time of the application uncomfortably long, but the blue spinning circle appears.
Even when the app finishes loading it persists. It only vanishes once you start moving the cursor.

**Comment by maroider** [comment] 2020-12-20 13:45
I think you may be confused as to which project you're reporting this issue against. Winit has no "hello-triangle" example.

Nevertheless, the issue you're describing is something I too have observed, but it's unclear what which piece of code is the culprit.

**Comment by kobutri** [comment] 2020-12-20 15:28
I’m sorry you are right. I meant to open this for wgpu-rs. It still seems to be an issue with winit rather than wgpu, so I leave it open for now.

**Comment by maroider** [comment] 2020-12-23 03:37
It seems like this is caused by a fault in the `WM_SETCURSOR` handler.

Even though the cursor is visibly inside the window, the `IN_WINDOW` flag isn't set in the `WindowState`, which makes the `WM_SETCURSOR` handler not set the cursor to the "arrow".

**Comment by maroider** [comment] 2020-12-23 05:23
I've gone ahead and made a tentative fix.
Could you check if my changes fix the issue for you, @kobutri?

**Comment by kobutri** [comment] 2020-12-23 13:56
Yes it works. Thanks for the fix.

**Comment by maroider** [comment] 2020-12-23 20:36
Do you mind re-opening this and keeping it open until #1807 is merged?
I'd also like you to try the newest set of changes, since the first set was buggy.

**Comment by kobutri** [comment] 2021-01-02 17:12
I tested the revised version. It seems fine to me.

**Closed** 2021-01-05 16:39 UTC
Labels: platform: Windows
