### ISSUE TITLE
ControlFlow::Exit stops the whole program in windows

### ISSUE THREAD

**Issue by ozgrakkurt** [rust-windowing/winit#1472] opened 2020-02-17 10:25 UTC
winit version: 0.21.0
rustc version: 1.41.0 (5e1a79984 2020-01-27)
os: windows 10

I have this code:
```rust
fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title("vktutorial")
        .with_inner_size(PhysicalSize::new(1280, 720))
        .with_resizable(false)
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                *control_flow = ControlFlow::Exit;
            }
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            Event::RedrawRequested(_) => {
            }
            _ => (),
        }
    });

    println!("TEST TEST TEST");
}
```

I expect this to print "TEST TEST TEST" when I close the window. But It just stops the program without printing anything. Also drop implementation of a struct is never run when I create an instance before calling event_loop.run.

**Comment by ozgrakkurt** [comment] 2020-02-17 10:53
I looked into the code and saw a call to std::process:exit(0). I am trying to use winit with vulkan. I created a struct which holds vulkan object and they have drop implementations so I want them to be run when the loop exits. Is there a way to achieve this?

**Comment by sanbox-irl** [comment] 2020-02-17 17:41
Three thoughts:
1. I believe this is intended.
2. If you move your game world (including your renderer, or whatever is holding your VK handles) into the loop, which is what you're supposed to do, then they will run drop when the loop is ended. For example, I did the following:

```rs
struct Marker;
impl Drop for Marker {
    fn drop(&mut self) {
        println!("Hello from the drop!");
    }
}

```
and then moved it into my event loop with the following:
```rs
let marker = Marker;

event_loop.run(move |event, _, control_flow| {
    let my_marker = &marker;
    // -- snip
}
```

And we succesfully see `drop` get ran at game close. You'd all get help for the VK layers doing something similar.

Note, as the Docs here <https://docs.rs/winit/0.21.0/winit/event_loop/struct.EventLoop.html#method.run> show, because winit is hijacking the thread, if you don't pass something into the control flow, its drop will not be ran (as you simulated). This could probably be highlighted more obviously! It's just a single line on *one* of the functions.

3. You're probably reading all of this and being like "jesus man I just want to make a video game." If you're targeting desktop platforms, you might want to look here <https://docs.rs/winit/0.21.0/winit/platform/desktop/trait.EventLoopExtDesktop.html#tymethod.run_return>. There are some funky things with run-return regarding resizing, but most games don't let you arbitrarily resize the window anyway, so they're not really a huge concern.

**Comment by goddessfreya** [comment] 2020-02-17 19:54
Thank you @sanbox-irl for that type up.

@ozgrakkurt This behavior is intentional. Closing as it is not a bug.

**Closed by goddessfreya** 2020-02-17 19:54 UTC
Labels: status: wontfix, type: api

**Comment by ozgrakkurt** [comment] 2020-02-18 08:58
@sanbox-irl thank you

**Comment by siavashserver** [comment] 2020-02-28 14:09
@goddessfreya why is that intentional?

> @ozgrakkurt This behavior is intentional. Closing as it is not a bug.

**Comment by OvermindDL1** [comment] 2020-03-02 17:39
@siavashserver Look at the rest of @goddessfreya's post that you did not quote:

> Thank you @sanbox-irl for that type up.

And indeed @sanbox-irl does give a basic overview of why this is.

In short:

`EventLoop::run` is purely event based and the program is killed when it returns via `ControlFlow::Exit`, this is to have identical running characteristics on all supported operating systems (of which multiple will kill your app as soon as you exit the event loop).  If winit did not do this then things like destructors not being run when exiting and not closing handles and more would be major issues.

If you want to be able to return from the method, which will only work on operating systems that support returning from an event loop (such as the major desktop OS's like Windows, Mac, and Linux's main environments (though not all of their environments)) then you want to use `EventLoop::run_return`.

This is all documented, and thus this is intentional and by design so the API works across all supported operating environments.

**Comment by siavashserver** [comment] 2020-03-03 10:11
Thanks!
