### ISSUE TITLE
Request a way intercepting winit's windows message handling

### ISSUE THREAD

**Issue by Icemic** [rust-windowing/winit#3175] opened 2023-10-23 10:10 UTC
I want to implement a function that stop the window from propagate keyboard event to global(system) to avoid emitting some global hotkey, such as winkey, winkey+r or something else like them.

For common winapi programming, a solution is to use `SetWindowsHookExW` registering a external handler and telling system this event is consumed. here is the code:

```rust
unsafe extern "system" fn low_level_keyboard_proc(
    n_code: i32,
    w_param: WPARAM,
    l_param: LPARAM,
) -> LRESULT {
    if n_code as u32 == HC_ACTION {
        let p_key_board: *const KBDLLHOOKSTRUCT = std::mem::transmute(l_param);
        log::info!("key pressed: {:?}", &*p_key_board);
        match w_param.0 as u32 {
            WM_KEYDOWN | WM_SYSKEYDOWN | WM_KEYUP | WM_SYSKEYUP => {
                if (&*p_key_board).vkCode == VK_LWIN.0 as u32
                    || (&*p_key_board).vkCode == VK_RWIN.0 as u32
                {
                    log::info!("windows key pressed");
                    // Consume the Windows key press
                    return LRESULT(1);
                }
            }
            _ => {}
        }
    }
    CallNextHookEx(HHOOK(0), n_code, w_param, l_param)
}

pub struct KeyboardHook {
    hhook: HHOOK,
}

impl KeyboardHook {
    pub fn perform() -> Self {
        // get h_instance
        let h_instance = unsafe { GetModuleHandleW(None).expect("failed to get module handle") };

        let hhook = unsafe {
            SetWindowsHookExW(WH_KEYBOARD_LL, Some(low_level_keyboard_proc), h_instance, 0)
                .expect("failed to set keyboard hook")
        };

        KeyboardHook { hhook }
    }
}

impl Drop for KeyboardHook {
    fn drop(&mut self) {
        unsafe { UnhookWindowsHookEx(self.hhook).ok() };
    }
}
```

however it does not work with winit. I think it is because [winit set a custom message handling function](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/window.rs#L1341) so even if i have hooked the 'original' one it makes no sense.

And i then need a way to `return 1` for some keys in the custom function instead of [always returning 0](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/event_loop.rs#L1046).

(In theory it is ok to return 0 because the event will reach hooks later since it is not consumed, but i don't know why it doesn't)

Is there a way to do so? Or is there a another way meeting my needs?

**Comment by Icemic** [comment] 2023-10-23 10:13
In fact, what i need is a function just like [Web's Keyboard lock API](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/lock). So maybe a new method `window.set_keyboard_lock(keys)` could be added?

**Comment by daxpedda** [comment] 2023-10-24 08:46
I believe this is a duplicate of #2776, let me know if I'm wrong about that.

**Closed by daxpedda** 2023-10-24 08:46 UTC

**Comment by Icemic** [comment] 2023-10-24 10:18
> I believe this is a duplicate of #2776, let me know if I'm wrong about that.

Yes, you are right. This proposal is basically equivalent to what I want.
I noticed that you marked my issue `not planned`, does it means there is no plan to provide a _intercepting way_, but a similar proposal _inhibiting system shortcuts_ is under consideration?

If so I'll look into it and see if there's anything I can do.

**Comment by JoshLambda** [comment] 2024-11-14 19:10
You can use the crate [global-hotkey](https://crates.io/crates/global-hotkey), it works properly with winit to intercept and consume key presses.

> I think it is because [winit set a custom message handling function](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/window.rs#L1341)

Just a note, your links point to the branch `master` but files have changed since, which means they now point toward random code.
