### ISSUE TITLE
Queston about one event struct

### ISSUE THREAD

**Issue by InnocentusLime** [rust-windowing/winit#1627] opened 2020-07-18 11:04 UTC
I've been looking through docs for `WindowEvent` and found the following definiton:

```rust
ScaleFactorChanged {
    scale_factor: f64,
    new_inner_size: &'a mut PhysicalSize<u32>,
},
```

I have several questions
1. Why is `new_inner_size` a mutable reference? That seems **really** weird
2. Why is it a reference at all? Why not just make it a value?

If there are no reasons, I'd like to make a PR to fix that... After all it will potentially make `WindowEvent` `'static + Clone + Copy`. Not only that. It seems like the whole `Event` struct will become `Clone + 'static`. Maybe even `Copy`!

**Comment by kchibisov** [comment] 2020-07-18 11:11
duplicate of https://github.com/rust-windowing/winit/issues/1387

**Comment by kchibisov** [comment] 2020-07-18 11:12
There were some work to resolve that but it seems like it got stalled.

https://github.com/rust-windowing/winit/pull/1456

**Closed by kchibisov** 2020-07-18 11:11 UTC
