### ISSUE TITLE
Intermittent hangs on Windows when using ControlFlow::Poll

### ISSUE THREAD

**Issue by ThatsNoMoon** [rust-windowing/winit#1522] opened 2020-04-05 03:01 UTC
Running a minor adaptation of the `window` example using `ControlFlow::Poll` leads to intermittent hangs on Windows (10.0.18362), wherein `winit` dispatches `NewEvents(Poll)`, `MainEventsCleared`, and `RedrawEventsCleared` continuously, causing Windows to treat the window as not responding, until `winit` dispatches a `Resized` `WindowEvent` with the same size as the window had before.
```rs
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    simple_logger::init().unwrap();
    let event_loop = EventLoop::new();

    let window = WindowBuilder::new()
        .build(&event_loop)
        .unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;
        log::debug!("event: {:?}", event);

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::WindowEvent {
                event: WindowEvent::Resized(size),
                ..
            } => log::warn!("Resized to {:?}", size),
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            _ => (),
        }
    });
}
```
Here's the section of the log output around where the hang stopped:
```
2020-04-04 21:03:06,610 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,610 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,611 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,611 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,611 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,611 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,611 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,615 DEBUG [window] event: WindowEvent { window_id: WindowId(WindowId(0x170a68)), event: Resized(PhysicalSize { width: 1024, height: 768 }) }
2020-04-04 21:03:06,615 WARN  [window] Resized to PhysicalSize { width: 1024, height: 768 }
2020-04-04 21:03:06,619 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,619 DEBUG [window] event: RedrawRequested(WindowId(WindowId(0x170a68)))
2020-04-04 21:03:06,620 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,620 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,620 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,620 DEBUG [window] event: RedrawRequested(WindowId(WindowId(0x170a68)))
2020-04-04 21:03:06,621 DEBUG [window] event: RedrawEventsCleared
```
Little information to be gained from the log from when the hang started:
```
2020-04-04 21:03:06,210 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,210 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,211 DEBUG [window] event: RedrawRequested(WindowId(WindowId(0x170a68)))
2020-04-04 21:03:06,211 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,212 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,212 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,213 DEBUG [window] event: RedrawRequested(WindowId(WindowId(0x170a68)))
2020-04-04 21:03:06,215 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,215 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,215 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,218 DEBUG [window] event: RedrawEventsCleared
2020-04-04 21:03:06,219 DEBUG [window] event: NewEvents(Poll)
2020-04-04 21:03:06,219 DEBUG [window] event: MainEventsCleared
2020-04-04 21:03:06,220 DEBUG [window] event: RedrawEventsCleared
```
`winit` also doesn't appear to dispatch any other events, like keyboard or mouse events, while it's in this "loop".

**Comment by filnet** [comment] 2020-04-09 13:29
Seems related to https://github.com/rust-windowing/winit/issues/1477

**Comment by notviri** [comment] 2020-04-13 09:38
Getting this as well on Windows 10 Version 1809 (build 17763.1098) 😢

**Comment by Osspial** [comment] 2020-04-19 18:20
I'm closing this as a duplicate of #1477. Still, thanks for reporting it!

**Closed by Osspial** 2020-04-19 18:20 UTC
Labels: platform: Windows, status: needs investigation, type: bug
