### ISSUE TITLE
media query doesn't match, Firefox 122.0b3

### ISSUE THREAD

**Issue by mikedilger** [rust-windowing/winit#3345] opened 2023-12-31 08:40 UTC
WASM,  Firefox Developer Edition 122.0b3 (64-bit)

````
panicked at /home/mike/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.7/src/platform_impl/web/web_sys/resize_scaling.rs:129:9:
created media query doesn't match, 1 != 1
````

Clearly these are floats very close to 1. I don't know why they don't match.  Same code works fine on Firefox 121.0.  I don't know which version of the browser this started with because I'm coming in fresh with a new project.

If it's a bug in firefox, just let me know.

**Comment by daxpedda** [comment] 2024-01-02 11:03
Would you mind trying this with the new v122.0b4 version and see if this is still triggered?
Which device did you use to produce this error?
What is the value of `Window.devicePixelRatio` for you?

I have to assume this is a bug though, because we aren't actually comparing any floats, we are simply using the value given to use by `Window.devicePixelRatio` in the `MediaQueryList`, which should match exactly.

**Comment by mikedilger** [comment] 2024-01-02 19:44
Just installed v120.0b4 and it still happens.

09:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)

DEVICE PIXEL RATIO = 1   (as u64 bits, that float is 4607182418800017408)

**Comment by daxpedda** [comment] 2024-01-02 21:17
> 09:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)

I meant the device in the sense of a Desktop/Mobile/Tablet, which OS and such.

> DEVICE PIXEL RATIO = 1 (as u64 bits, that float is 4607182418800017408)

Could you enter `window.devicePixelRatio` in your browser dev console and post the output?

Also try the following and post what it returns:
1. ```js
   const mql = window.matchMedia('(resolution: ' + window.devicePixelRatio + 'dppx)')
   mql.matches
   ```
2. ```js
   const mql = window.matchMedia('(-webkit-device-pixel-ratio: ' + window.devicePixelRatio + 'dppx)')
   mql.matches
   ```
3. ```js
   const mql = window.matchMedia('(resolution: ' + window.devicePixelRatio + 'dppx), (-webkit-device-pixel-ratio: ' + window.devicePixelRatio + 'dppx)')
   mql.matches
   ```

**Comment by mikedilger** [comment] 2024-01-02 21:40
Ok. It a desktop computer, AMD Ryzen, running ArchLinux 6.6.8-arch1-1 with Xfce and X11 backend (not wayland)

```
window.devicePixelRatio
1
```

1. false
2. false
3. false

( had to rename to mql2 and mql3 and test mql2.matches and mql3.matches to avoid redecl of a const)

**Comment by daxpedda** [comment] 2024-01-02 21:53
Alright, it clearly is a bug then.

1. Do you happen to have more then one display? (see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1468037))
2. Could you try:
   ```js
   const mql = window.matchMedia('(-webkit-device-pixel-ratio: ' + window.devicePixelRatio + 'dppx)')
   ```
   and wait a second before using `mql.matches`? (just to make sure this is not a delay issue)
3. Would you mind creating a bug report at https://bugzilla.mozilla.org, considering I can't recreate the issue on my end?

**Comment by mikedilger** [comment] 2024-01-02 22:25
firefox-developer-edition, FRESH PROFILE, `dom.webgpu.enabled` to true:
   The answers are  (false, false, true)
   My app errors at "webgpu not available or canvas already in use", which is further into the code.

So something about my firefox profile makes the difference. Maybe some privacy setting?

I tried your three matchMedia statements in the new profile, and the first 2 are false but the 3rd one is true.

Yes I do have more than 1 display.

**Comment by daxpedda** [comment] 2024-01-02 22:30
Interesting, so it seems a fresh profile has fixed the issue.
It would be interesting to figure out which exact setting has caused this, especially to create a bug report.

In the meantime I will close this as from Winit's perspective this is resolved, please feel free to update us in this issue though!

**Comment by mikedilger** [comment] 2024-01-02 22:33
It is `privacy.resistFingerprinting`. When I disable this, the media query comes back as true.

I think winit should not panic in this situation.

**Comment by daxpedda** [comment] 2024-01-02 23:43
Okay, interesting.

> I think winit should tolerate this situation instead of giving up with an Err

Agreed, will come up with a patch tomorrow.
Just to drop some thoughts:
My guess is that Firefox's `privacy.resistFingerprinting` option entirely disables getting the scale factor, but I will have to figure that out. If this is the case, we just need to disable the whole scale factor code if it's not supported.

**Comment by daxpedda** [comment] 2024-01-03 08:31
@mikedilger I still can't reproduce this issue.
I did set `privacy.resistFingerprinting` to true, but
```js
const mql = window.matchMedia('(resolution: ' + window.devicePixelRatio + 'dppx)')
mql.matches
```
still returns `true` for me. Are you sure you didn't change any other settings?

Could you try to change your DPI on the OS level and see what `window.devicePixelRatio` reports?

---

I have to say that this is still a bug in Firefox, as I don't see how not supporting `resolution` in `MediaQueryList` correctly improves fingerprinting resistance. If the intent is to always report `window.devicePixelRatio` as 1, which would indeed improve fingerprint resistance, `resolution` should still be supported, it should just be 1.

Will write up a bug report as soon as I can reproduce this issue.

Additionally, I don't think setting `privacy.resistFingerprinting` is recommended anymore. I assume that you got that information from the ["Firefox's protection against fingerprinting" article](https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting#firefox:linux:fx117). But this was changed at v118, see [the new article](https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting). I assume that this option is now accessible through the settings interface, which as far as I could tell doesn't change `privacy.resistFingerprinting` directly.

**Comment by mikedilger** [comment] 2024-01-06 20:09
With `privacy.resistFingerprinting` on, I get:

```
>> window.devicePixelRatio
<- 1
>> window.matchMedia('(resolution: ' + window.devicePixelRatio + 'dppx)')
<- MediaQueryList { media: "(resolution: 1dppx)", matches: false, onchange: null }
```

With `privacy.resistFingerprinting` off, I get:

```
>> window.devicePixelRatio
<- 1.2
>> window.matchMedia('(resolution: ' + window.devicePixelRatio + 'dppx)')
<- MediaQueryList { media: "(resolution: 1.2dppx)", matches: true, onchange: null }
 ```

It is true I have a lot of other non-default settings, but just flipping this one switch makes this change.

Changing my dpi using xrandr "--scale" and "--dpi" didn't make a difference, and xfce4 doesn't have a way to modify global DPI (only things like font scaling)

I also think it is a firefox bug.

**Comment by daxpedda** [comment] 2024-01-06 20:23
I created #3345 to deal with this.

Nevertheless I recommend you to file a bug report at [Mozilla Bugzilla](https://bugzilla.mozilla.org) to get this fixed. Otherwise it might cause more bugs that can't be easily accounted for.

**Closed** 2024-01-06 22:05 UTC
Labels: DS - wasm, B - crash

**Comment by mikedilger** [comment] 2024-01-07 21:17
filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1873382
