### ISSUE TITLE
Force Touch causes weird behavior

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/winit#63] opened 2016-11-03 08:03 UTC
Original: https://github.com/tomaka/glutin/issues/672

**Comment by madsmtm** [comment] 2023-08-24 13:22
I tried reproducing this, and found that doing a force touch causes `WindowEvent::MouseInput` to be delivered just as if I didn't do the force touch at all; so I'm going to close this, since I suspect it's no longer relevant, and have been fixed at some point in the last 7 years.

**Closed by madsmtm** 2023-08-24 13:22 UTC
Labels: B - bug, H - help wanted, DS - macos, C - needs investigation, D - average, P - low
