### ISSUE TITLE
winit suddenly requires `cmake` dependency

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-windowing/winit#2373] opened 2022-07-14 13:25 UTC
It looks like ever since `sctk-adwaita` got upgraded (and their dependencies got upgraded) this crate is dragging in `cmake`, polluting everybody's build system and setup. Our project has a zero-tolerance policy for `cmake` (or other build time tools since we just want to be able to build trough `cargo` with no additional tools required to be set up).

Dependency tree seems to be:

`sctk-adwaita` ->`crossfont` -> `servo-fontconfig` -> `servo-fontconfig-sys` -> `expat-sys` -> `cmake`

Presumably all of this isn't strictly required and can be disabled?

**Comment by Jasper-Bekkers** [comment] 2022-07-14 13:49
> Just disable sctk-adwaita feature? Or install system headers for fontconfig, freetype?

Honestly if sctk-adwaita drags in such major dependencies, I don't think it should be enabled by default

**Comment by kchibisov** [comment] 2022-07-14 13:55
The point to have decorations that make sense on Wayland. Like you know, that you will have a text in your title bar. That's the main point to provide sensible defaults. Otherwise you'll be surprised that your window suddently doesn't have a title bar or actual buttons.

If anything we can abort compilation if you don't have system library headers installed.

**Comment by Jasper-Bekkers** [comment] 2022-07-14 14:04
I don't think any of that is needed, sensible titlebars are very welcome, however, that can all be achieved without reliance on `cmake` (and by having a sensible build setup).

**Comment by kchibisov** [comment] 2022-07-14 14:08
Well, bring it to whoever builds those system crates and requires to put the entire thing just to build it just in case?

I'll alter to just abort. So you won't have a cmake problem.

**Comment by kchibisov** [comment] 2022-07-14 22:18
>On alternative might be to swap out servo-fontconfig with fontconfig/yeslogic-fontconfig, which doesn't fall back to vendoring fontconfig and expat when it can't find a compatible version of fontconfig at build time, but that's a decision to make for whoever is maintaining crossfont.

Servo does the same thing. That's the point. The issue is that it fallbacks. We have a flag in crossfont to not ever fallback here, which is what they want. I've patched sctk-adwaita to use that flag instead, but it'll have time for it to release. 

>whoever is maintaining crossfont.

It's alacritty's project, so it's kind of me.

**Comment by kchibisov** [comment] 2022-07-19 15:37
Reopening since we want to force system libraries.

**Comment by MarijnS95** [comment] 2022-07-20 10:17
It seems to still pull in `cmake`:

```console
$ cargo tree -i cmake
cmake v0.1.48
[build-dependencies]
├── expat-sys v2.1.6
│   └── servo-fontconfig-sys v5.1.0
│       └── servo-fontconfig v0.5.1
│           └── crossfont v0.5.0
│               └── sctk-adwaita v0.4.1
│                   └── winit v0.26.1 (https://github.com/rust-windowing/winit?rev=f09259f6#f09259f6)
│                       ...
└── freetype-sys v0.13.1
    ├── freetype-rs v0.26.0
    │   └── crossfont v0.5.0 (*)
    └── servo-fontconfig-sys v5.1.0 (*)
```

At the same time the requirement for `pkg-config` makes me unable to cross-compile `winit` for an aarch64 platform where I don't have `pkg-config` support (yet, could be added but it's a hassle), nor Android it seems.

Fortunately we can circumvent both issues by disabling Client-Side Decorations, as we don't render any of those.

**Comment by kchibisov** [comment] 2022-07-20 10:41
I'm pretty sure you can use env variable for pkg-config to cross it. I've been doing so for a long time in alacritty.

**Comment by kchibisov** [comment] 2022-07-20 10:49
You're cross compiling for linux, not android, right? Since none of that should be triggered for android target.

If @maroider thinks that we shouldn't have any fancy decorations on Wayland by default, then we can swap defaults.

**Comment by maroider** [comment] 2022-07-20 10:52
I feel like the default should be what works best for the most amount of people, and that seems to me like it would require the fancy decorations.

**Comment by MarijnS95** [comment] 2022-07-21 09:40
> You're cross compiling for linux, not android, right? Since none of that should be triggered for android target.

Correct, `aarch64-unknown-linux-gnu`. I don't remember what I was doing when writing "nor Android it seems" yesterday, because it is definitely compiling just fine.

> I'm pretty sure you can use env variable for pkg-config to cross it.

Allowing it is easy, but I'll have to pull the `.pc` files and libraries from the target machine to make it link. Not the end of the world, but a hassle nonetheless.

---

Regarding decorations, I wanted to ask if these ugly non-GNOME borders are also caused - and fixed - by this feature on wayland?:

![image](https://user-images.githubusercontent.com/2325264/180180477-e39acdd8-4b29-40b8-bbd1-57f179ae0064.png)

That'd be an incentive for me to set that up. I've only used this application on Sway thus far without any window borders and didn't notice.

In order to rule out any issues in my application I tried the winit examples. But none actually show a window on neither my x64+sway desktop nor aarch64+GNOME "phone" (both on Wayland)? Not even when going back to `v0.26.1`. @kchibisov are the examples missing any kind of event handling or `Window` setup that make it work properly?

**Comment by kchibisov** [comment] 2022-07-21 10:05
@MarijnS95 winit examples are not showing anything on Wayland unfortunatelly, since you should draw on Wayland to make your window visible, but none of the examples are drawing anything. It's recommended to use glutin examples here.

>Regarding decorations, I wanted to ask if these ugly non-GNOME borders are also caused - and fixed - by this feature on wayland?:

Yes, the goal is to provide more visually pleasant decorations. That's how they look.

![picture](https://user-images.githubusercontent.com/27620401/180187939-049bd565-d723-4302-ad34-2b119f6b21d6.png)


They also have a light variant(you can control that when building a window in winit or by using environment variable).

The decorations on GNOME will always be non-native, since winit isn't using gtk and won't do so. But drawing something similar looking or at least with text is preferred imho, like we do now.

**Comment by MarijnS95** [comment] 2022-07-21 13:26
@kchibisov Thanks for explaining, you mentioned `softbuffer` before so it'd be good to have _some_ solution to make the examples run on Wayland again.

Indeed, after setting up cross-compilation for these libs through `pkg-config` the window borders are more pleasant again.

I just expected the window manager and compositor to take care of and be able to render them natively (if the application doesn't request custom rendering). Guess I have more to learn about them - or specifically Wayland?

**Comment by MarijnS95** [comment] 2022-07-21 13:27
However, back to the original issue: `cmake` is still in the dependency graph, despite stating in #2381:

> This should force the use of system libraries for Fontconfig
? and freetype instead of building them with cmake if missing.

**Comment by kchibisov** [comment] 2022-07-21 14:16
>I just expected the window manager and compositor to take care of and be able to render them natively (if the application doesn't request custom rendering). Guess I have more to learn about them - or specifically Wayland?

GNOME refuses to support server-side decorations. So we must draw something ourselves.

>However, back to the original issue: cmake is still in the dependency graph, despite stating in https://github.com/rust-windowing/winit/pull/2381:

IIRC it's still there, but not used anymore. Is it causing issues?

**Comment by MarijnS95** [comment] 2022-07-21 14:24
It seems like `expat-sys` is still trying to invoke it...

**Comment by kchibisov** [comment] 2022-07-21 14:25
Hm, That's unfortunate.

**Comment by MarijnS95** [comment] 2022-07-21 14:31
https://github.com/servo/libfontconfig/blob/master/Cargo.toml Looks like this is where the `force_system_lib` feature isn't propagated into `expat-sys` nor `freetype-sys`, only `fontconfig`'s `pkg-config` error is non-fatal based on that.

**Comment by kchibisov** [comment] 2022-07-21 14:38
Freetype won't build with cmake, look at its build.rs. However expat I think can. The original flag was added to mitigate fontconfig from building.

**Comment by MarijnS95** [comment] 2022-07-23 21:47
> Freetype won't build with cmake, look at its build.rs.

It still pulls in this dependency into the tree even if unlikely to be ran thanks to the env var; it should just be guarded by a feature toggle as well or instead.

**Comment by LoganDark** [comment] 2022-07-24 08:42
> The point to have decorations that make sense on Wayland. Like you know, that you will have a text in your title bar. That's the main point to provide sensible defaults. Otherwise you'll be surprised that your window suddently doesn't have a title bar or actual buttons.

Why does winit need to support degenerate display managers without server-side decorations? Do those exist on real desktop systems?

**Comment by MarijnS95** [comment] 2022-08-09 15:52
@kchibisov I think both crates can be reworked to make `cmake` optional, but we can't base it on `force_system_lib` since that'd require an inversion in `Cargo.toml` which I don't think is possible (enable the _optional_ `cmake` crate when `force_system_lib` is _not_ set).

Instead we might have to have a `cmake` feature, and replace `force_system_lib` with `enable_cmake` or something similar in `libfontconfig`.

Thoughts?

**Comment by alexheretic** [comment] 2022-08-13 16:57
Yeah this was a bit of a pain building my game in ubuntu:16.04 (to maintain compat) where cmake is too old to work with freetype-sys. Working around that, by dling newer cmake, I faced bundling additional libs with my game to solve linking failures across the distros I support _(libfontconfig.so.1, libfreetype.so.6, libpng12.so.0, libexpat.so.1)_.

I think I can make that work, but it's fairly high effort to render a 2 word wayland title. In the end I went with the `wayland-csd-adwaita-notitle` feature. It would be nice to have a rust-text alternative to freetype option for wayland titles, perhaps that can be added to _sctk-adwaita_?

**Comment by PolyMeilex** [comment] 2022-08-14 17:09
Although this was already mentioned here, I'll say it anyway:
If you want to eliminate the system dependency, just use `wayland-csd-adwaita-notitle` there is no reason to remove all of the decorations. Rendering decorations is done in pure rust, so you can still keep the "fancy" decorations, and just drop the title.
To quote the changelog:
- `wayland-csd-adwaita` feature that enables proper CSD with title rendering using FreeType system library.
- `wayland-csd-adwaita-notitle` feature that enables CSD but without title rendering.

---

That being said, Alex's `ab_glyph` version of title rendering got merged in `sctk-adwaita` already, and I will release it shortly, so `winit` could expose this option as well, but that's not for me to decide.

**Comment by john01dav** [comment] 2022-08-24 01:58
> but it's clear now that softbuffer isn't a good project in terms of quality, so we should add something our selves

Hi, softbuffer developer here. Would you be willing to share what your issues with it are? I had some issues relating to my employment contract with a new employer that made FOSS contributions a bad idea so I had to let some issues & PRs sit, but the contract issues are resolved now so I'm starting to process the backlog.

@kchibisov

**Comment by kchibisov** [comment] 2022-08-24 02:04
@john01dav I'd suggest to contact @i509VCB on that regard wrt Wayland.

Wrt X11 we had issues here https://github.com/rust-windowing/winit/pull/2246.

**Closed** 2022-08-24 12:24 UTC
