### ISSUE TITLE
EventLoop::new should be fallible

### ISSUE THREAD

**Issue by Ralith** [rust-windowing/winit#1212] opened 2019-10-05 15:46 UTC
Creating a window is not critical to my application, so if e.g. there's no display server installed or libX11 isn't in the library search path winit shouldn't panic and bring down my process.

**Comment by ryanisaacg** [comment] 2019-10-15 16:33
Relevant: #500

**Comment by madsmtm** [comment] 2023-01-23 14:48
Duplicate of https://github.com/rust-windowing/winit/issues/500

**Closed by madsmtm** 2023-01-23 14:48 UTC
Labels: type: enhancement
