### ISSUE TITLE
DeviceEvent::Motion not emitted on Wayland

### ISSUE THREAD

**Issue by AustinJ235** [rust-windowing/winit#1595] opened 2020-06-05 20:54 UTC
I am not receiving `DeviceEvent::Motion` when using wayland.

- Winit 0.22.2
- Compositor: gnome 3.36 or sway 1.4
- Distro: Arch
- Mesa: 20.2.0 (git c183ea94afd)
- Kernel: 5.6.16
- wayland: 1.18.0
- wayland-protocols:  1.20

**Comment by AustinJ235** [comment] 2020-06-05 20:59
They were emitted in the past with winit. I just noticed that no longer are.

**Comment by kchibisov** [comment] 2020-06-05 21:00
It might be an impl oversight, but you don't get any events outside of your window at all anyway.

**Comment by AustinJ235** [comment] 2020-06-06 02:05
An oversight on winit's part or compositors? Mainly I need this for camera inputs where direct input is desired versus with the desktop's acceleration and sensitivity.

**Comment by Abendstolz** [comment] 2020-06-06 19:18
To chip in: I still get `DeviceEvent::MouseMotion` (I too use Sway 1.4) - I am using the latest released version from `crates.io`, so also `Winit 0.22.2` (checked my `Cargo.lock` to be sure)

My 0.05 regarding this topic: I actually opened https://github.com/rust-windowing/winit/issues/1594 just yesterday.

If I don't get `Device::MouseMotion` events on `Wayland` anymore this would break my entire application (and I think I am not alone with this).
To explain why:
When `set_cursor_grab(true)` doesn't emit  any more `WindowEvent::CursorMoved` on `wayland` (see my reported #1594) 

but **even if it did** this would **not suffice**! Why? There is no `set_cursor_position` on `wayland`, so I `Camera controls` in any game ***rely*** on `DeviceEvent::MouseMotion` because otherwise, if the cursor hits the bounds of the window, you could no longer turn, which leads to problems like the user not being able to turn around all the way!

To stretch this once more `DeviceEvent::MouseMotion` is ***absolutely necessary*** OR there needs to be a way to `set_cursor_position` so that `WindowEvent::CursorMoved` can be used instead.

Also use of `Device::MouseMotion` is necessary on `x11` as well (although one could `set_cursor_position` there to circumvent this - but then one would need to get rid of the `wayland` backend altogether when shipping a game, because it would `panic` on `set_cursor_position`)

One last thing, the docs themselves say to use `DeviceEvent::MouseMotion`, see: https://docs.rs/winit/0.22.2/x86_64-pc-windows-msvc/winit/event/enum.WindowEvent.html#variant.CursorMoved

> Because the range of this data is limited by the display area and it may have been transformed by the OS to implement effects such as cursor acceleration, it should not be used to implement non-cursor-like interactions such as 3D camera control.

Please take that into account for any changes regarding the `wayland` backend. I don't want to go back to having to always force `x11`, as `wayland` made huge leaps in the last couple of years - so kudos and a huge thanks to you and all other contributors that made this possible!

(also if `wayland` becomes unusable again how the hell should I ship my game with `winit`? Should I tell every user to please set an environment variable and have `xwayland` installed? ;))

**Comment by kchibisov** [comment] 2020-06-06 19:31
>To chip in: I still get DeviceEvent::MouseMotion (I too use Sway 1.4) - I am using the latest released version from crates.io, so also Winit 0.22.2 (checked my Cargo.lock to be sure)

You get or you don't get? I guess `DeviceEvent::Motion` should be emitted right now after looking in winit code again, and I do get it as well on sway, while original issue states that it's not emitted.

>When set_cursor_grab(true) doesn't emit any more WindowEvent::CursorMoved on wayland (see my reported #1594)

This something that should be rechecked and understand what should be emitted from when grab is set and winit should explicitly define what it should emit when the grab is set.

>One last thing, the docs themselves say to use DeviceEvent::MouseMotion, see:

That's what emitted right now for me on Wayland when cursor grab is set, and not without it, since Wayland is just different.

>(also if wayland becomes unusable again how the hell should I ship my game with winit? Should I tell every user to please set an environment variable and have xwayland installed? ;))

I guess you check dependencies you're using before adding to your project and I hope that you can spot such things during testing. Also you just statically link your game to a specific version of winit, which is known to work. If something will be changed it's up to you to read changelogs and test. it's not dynamic linking, etc.

     
>Please take that into account for any changes regarding the wayland backend. I don't want to go back to having to always force x11, as wayland made huge leaps in the last couple of years - so kudos and a huge thanks to you and all other contributors that made this possible!

Wayland backend requires some polishing and updates, which I'll come back in July(can't do that earlier, sorry). It's know to work good enough right now for some projects like alacritty, but I do understand some issues right now and the solution is not that simple tbqh, since adding more code to existing code base isn't something I really like.

**Comment by Abendstolz** [comment] 2020-06-06 19:43
> > To chip in: I still get DeviceEvent::MouseMotion (I too use Sway 1.4) - I am using the latest released version from crates.io, so also Winit 0.22.2 (checked my Cargo.lock to be sure)
> 
> You get or you don't get? I guess `DeviceEvent::Motion` should be emitted right now after looking in winit code again, and I do get it as well on sway, while original issue states that it's not emitted.

I get `DeviceEvent::MouseMotion` (like you) on `sway`/`wayland` - in fact it's my workaround for #1594 - I am back to using
`set_cursor_grab(true)` along `DeviceEvent::Motion` on _all_ platforms (and I do hope that they work like expected on `Windows` and `MacOS` as well - but I cannot test :)

> > One last thing, the docs themselves say to use DeviceEvent::MouseMotion, see:
> 
> That's what emitted right now for me on Wayland when cursor grab is set, and not without it, since Wayland is just different.
> 
> > (also if wayland becomes unusable again how the hell should I ship my game with winit? Should I tell every user to please set an environment variable and have xwayland installed? ;))
> 
> I guess you check dependencies you're using before adding to your project and I hope that you can spot such things during testing. Also you just statically link your game to a specific version of winit, which is known to work. If something will be changed it's up to you to read changelogs and test. it's not dynamic linking, etc.

You're right. The problem is that `winit` is a pretty integral part of any application right now and it's pre 1.0, so when I decide to "freeze" my winit, I can basically also freeze a lof of other dependencies.

So while you're right that for an actual release I should (and will) pin the version to something well-tested, this is not something I can do right now - especially as fixes for other platforms would not be backported to my specific version ;)

 
> > Please take that into account for any changes regarding the wayland backend. I don't want to go back to having to always force x11, as wayland made huge leaps in the last couple of years - so kudos and a huge thanks to you and all other contributors that made this possible!
> 
> Wayland backend requires some polishing and updates, which I'll come back in July(can't do that earlier, sorry). It's know to work good enough right now for some projects like alacritty, but I do understand some issues right now and the solution is not that simple tbqh, since adding more code to existing code base isn't something I really like.

Don't get me wrong here: I highly appreciate all the efforts put into `winit` and especially the `wayland` backend - as that's the one I interact with the most. I don't expect anything from you or any other contributor. I am well aware that this is a side-project and not a full-time job and it's something that should be fun among other things.

The only thing I wanted to say is: Before anything is decided, please take into account how other platforms are behaving, _especially_ `X11` as the decision between `X11` and `wayland` is made at runtime in `winit` (in contrary to e.g. `glfw` where at least on my system I can either install `glfw-x11` XOR `glfw-wayland`)

So as it works now is fine for me, it's just that either the docs should be adapted (because some behaviour is surprising, like a `panic` on wayland) or that the logic should be streamlined between `X11` and `wayland` (in regards to #1594)

I hope this clarified my wording - I am sorry, I am a non-native speaker, no offense was meant in any way!

**Comment by kchibisov** [comment] 2020-08-28 07:02
Closing in favor of #1678 and #1677

**Closed by kchibisov** 2020-08-28 07:02 UTC
Labels: platform: Wayland, status: needs investigation
