### ISSUE TITLE
Focus event order on Windows

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#817] opened 2019-03-18 21:59 UTC
While trying to fix https://github.com/jwilm/alacritty/issues/2170, I've just noticed that the event order of the `Focused` event is a bit different on Windows compared to the other platforms.

Even though window focus on Windows can only be changed when clicking on a window, the `Focused` events comes *before* the `MouseInput` event. They aren't coming in the same bulk either so the order isn't only messed up but they're coming in completely disconnected from each other in short succession.

The issue with this is that it makes it impossible to determine if a `MouseInput` event was on a focused or unfocused window. So clicks on unfocused windows can't easily be ignored.

I'm not sure if this is an issue with winit or a constraint due to the Windows API, but this is probably the best place to ask.

**Comment by Osspial** [comment] 2019-03-19 02:19
I'm not aware of any clean way to deliver `MouseInput` before `Focused` - it would require some pretty hacky stuff on our end to get working, and I'm not comfortable with introducing that to the codebase. *However*, it should still be possible to fix the downstream behavior easily!

When I was looking into this, I found that someone had put in code that resulted in a [`CursorMoved(0, 0)` event getting dispatched whenever the window gained focus](https://github.com/tomaka/winit/blob/master/src/platform/windows/events_loop.rs#L1061-L1069), which is pretty clearly causing the selection bug in Alacritty. No idea why that was there - the [relevant documentation](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-setfocus) explicitly says that the variable they're trying to read as mouse position is unused, but removing that event dispatch is easy. I'll get a PR going to fix that ASAP.

**Comment by chrisduerr** [comment] 2019-03-19 16:42
As far as I'm concerned, fixing the issue is good enough at this point.

However by default on Windows the first click on a focused window is usually ignored, so selections should not be cancelled. At least cmd.exe and powershell behave this way.

For Alacritty that might not be a huge deal, but it might still be something that winit should support.

Always ignoring the first click after the focus has changed from unfocused to focused doesn't seem like an option either, since it's possible to focus a window without using the mouse.

Are you aware of any option a user of winit might have to resolve this? It seems impossible to determine if a click was what caused the focus or not.

**Comment by Osspial** [comment] 2019-03-20 21:49
Hmm. I tested it on ConEmu too, and it also ignores the first click on focus. I can look into what it's doing, since it's open source, and will get back to you on whether or not it's feasible for us to do. As far as I can tell that behavior only happens for console emulators (it didn't happen with Firefox or the various text editors I tried), but it seems there *is* a way to detect it.

I don't like the idea of officially defining the order of mouse/focus events since that's really a niche and finicky API guarantee to put in place, but I'm open to the idea of having some sort of API for determining if a click caused window focus. I don't know what said API should look like, though.

**Comment by chrisduerr** [comment] 2019-03-20 21:54
> I don't like the idea of officially defining the order of mouse/focus events since that's really a niche and finicky API guarantee to put in place, but I'm open to the idea of having some sort of API for determining if a click caused window focus.

I'd be perfectly fine with that. And as I've mentioned nobody has actually expressed the need for that on Windows *yet*. Though it has been explicitly requested on macOS (where we currently rely on the event order, which is correct).

I think keeping this issue open to track research into this area probably makes sense. I think it probably is something that should at least be investigated so an explicit decision can be made if this should be supported or not. I personally don't *really* care either way, but a clear and unified stance is always nice of course.

> one potential option in winit's current state would be to ignore any click events that happen in the same iteration of the main application loop, which wouldn't run into the issue of the first click getting ignored after an alt tab.

I've tried that. It does not actually work. The click event will not only come out of order in the same iteration, but sometimes come in a completely different (later) operation.

**Comment by Osspial** [comment] 2019-03-21 03:22
> I've tried that. It does not actually work. The click event will not only come out of order in the same iteration, but sometimes come in a completely different (later) iteration.

That's... odd. I wouldn't expect that to happen.

I've done some testing on the `eventloop-2.0` branch, and it seems like the click event is coming in the same iteration fairly consistently there - perhaps the behavior you're seeing is caused by some quirk in the code that was fixed in the refactor? Regardless, I elect to hold off new API investigations until the EL2.0 code lands on crates.io, and we can see if that fixes it. If it does that saves a whole lotta headache on our end.

**Comment by vberger** [comment] 2019-03-21 08:43
> I don't like the idea of officially defining the order of mouse/focus events since that's really a niche and finicky API guarantee to put in place, but I'm open to the idea of having some sort of API for determining if a click caused window focus. I don't know what said API should look like, though.

I expect this to be something quite difficult to achieve in a cross-platform way though. Not all platforms provide ordering guarantees wrt to that

**Comment by chrisduerr** [comment] 2019-03-21 16:10
Just to clarify, I've done my testing with the code that is currently on crates.io, not the latest git version.

> I expect this to be something quite difficult to achieve in a cross-platform way though. Not all platforms provide ordering guarantees wrt to that.

Having no ordering guarantee would be fine if the cursor click does not cause the focus event. On i3 for example just hovering over a window focuses it, so it's irrelevant there.

However if the click is what actually triggered the focus of the window, I think the click event should at least come in the same iteration as the focus event. Everything else just seems a bit bizarre, when the event that triggered something comes a whole iteration after what it has triggered.

Of course if the platform itself doesn't make it possible, winit's SoL. But just from a design PoV it makes no sense imho.

**Comment by vberger** [comment] 2019-03-21 17:04
> However if the click is what actually triggered the focus of the window, I think the click event should at least come in the same iteration as the focus event.

Agreed on that.

For the record, I expect this to already be the case on wayland, unless the server was designed in a very bizarre way. But We will not be able to make more precise guarantee on the ordering of the events wrt to each other.

**Comment by xStrom** [comment] 2019-04-01 23:45
> However by default on Windows the first click on a focused window is usually ignored, so selections should not be cancelled. At least cmd.exe and powershell behave this way.

I don't think it's that usual, my gut feeling is that it's mostly not ignored. I did some minor testing and it looks like all the older components don't ignore the click, even on Windows 10. So things like `explorer.exe` and `notepad.exe` handle that first focusing click. However the ribbon UI design era apps like `wordpad.exe` and `mspaint.exe` ignore it. Not completely though, the very top titlebar handles the click, including the floppy disk save button. That tradition of ignoring didn't hold long though as the UWP apps seem to once again handle the first click, e.g. `Calculator`, `Settings`, `Xbox`. Additional apps like `chrome.exe`, `firefox.exe`, `sublime_text.exe`, `Code.exe`, `vlc.exe` -- all handle the click. While others like `Photoshop.exe` don't.

Speaking as a user, I strongly prefer that the click is handled. I use multiple monitors with high resolutions. Which means I have a lot of apps visible even though they aren't focused. When I click on an app, as a rule it's to perform some function and the focusing part is merely a byproduct. Having to click twice would get old really fast.

In light of all this, I don't think winit should start hiding the click event. It's useful.

Now for the cases where ignoring might make sense in a specific app, the app developer could just record the time when the focus event arrives and ignore any clicks that happen say within the next 50 milliseconds.

**Comment by kchibisov** [comment] 2023-07-11 08:44
I think that it is fixed.

**Closed by kchibisov** 2023-07-11 08:44 UTC
Labels: DS - windows
