### ISSUE TITLE
Minimum Supported Rust Version

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/winit#1075] opened 2019-07-29 00:12 UTC
Back in https://github.com/rust-windowing/winit/issues/531 it seems that it was agreed to test against `1.24` in CI, and now [travis](https://github.com/rust-windowing/winit/blob/master/.travis.yml) and [appveyor](https://github.com/rust-windowing/winit/blob/master/appveyor.yml) just test against `stable`.

It would be better for the long term health of the community if foundational crates such as `winit` had a particular version number for minimum rust requirement. Could we move `winit` back in that direction? Since everyone is working on `winit-0.20` being a "big change" with event loop 2.0 and all that, it'd be nice to also use that as a time to transition back to a policy of having a specific minimum rust version and trying to be aware of when that minimum version goes up.

**Comment by ZeGentzy** [comment] 2019-07-29 03:51
Personally, it is of my opinion that we should support the last three stable rust versions, so 1.36, 1.35 and 1.34 currently. This was discussed between me and @chrisduerr in the past, but I never got around to updating the CI or [the readme.](https://github.com/rust-windowing/glutin#usage) I'm not really in favor of a MSRV.

**Comment by Lokathor** [comment] 2019-07-29 04:57
I've since had some additional information brought to my attention
* https://github.com/rust-windowing/winit/issues/743
* https://github.com/rust-windowing/winit/pull/746
* https://gitlab.redox-os.org/redox-os/stb_truetype-rs/issues/20

Now, I'm not asking that you always keep the same minimum rust version if your dependencies aren't willing to play along. However, it should be entirely possible for you at least go back to tracking a minimum version and then having any minimum version bumps force a breaking change version bump in your own release.

**Comment by chrisduerr** [comment] 2019-07-29 15:59
> Personally, it is of my opinion that we should support the last three stable rust versions, so 1.36, 1.35 and 1.34 currently. This was discussed between me and @chrisduerr in the past, but I never got around to updating the CI or the readme. I'm not really in favor of a MSRV.

I think this would be a great idea and offer quite a bit of room for users and distributions to update their systems. Note that I've proposed this policy based on a discussion with alexcrichton [here](https://github.com/rust-lang/backtrace-rs/issues/211#issuecomment-504970353). So winit wouldn't be first to adopt this policy.

I'd also like to note that this doesn't mean that winit can't support older versions, just that changing the minimum version to something older than the last three versions is not a breaking change.

This is an important detail to make maintenance and CI a bit easier. There's no need to bump winit's minimum supported CI version whenever a new Rust version is released, the CI can just stay on 1.20.0 for example but as soon as a change is required which updates to something that was not introduced in the last two rust versions, CI can just be bumped and everything's good again.

This policy would also mean that if there's really a necessity to update to something even more recent, that would be possible too. However, in that case it needs to clearly be marked as a breaking change so no downstream dependencies run into any issues. However I think generally this policy should be lax enough that this shouldn't usually be necessary, but it's an important tool to have to clearly communicate when this is the case.

**Comment by Lokathor** [comment] 2019-07-29 20:13
Well, code actually breaks. It worked one moment and doesn't after a `cargo update`.

That doesn't mean that you can't ever move your minimum rust version, just also reflect it as a breaking change in your version numbering.

**Comment by Osspial** [comment] 2019-07-29 20:44
We've gone through this before. I'm extremely wary about doing this without official support from Cargo (such as with https://github.com/rust-lang/rfcs/pull/2495), since it's pretty much impossible to enforce a MSRV if you have dependencies that don't enforce it.

> However, it should be entirely possible for you at least go back to tracking a minimum version and then having any minimum version bumps force a breaking change version bump in your own release.

Since we have dependencies that don't enforce a MSRV, this isn't feasible. If you have dependencies that are willing to bump the MSRV in patch releases (which we do), this sort of policy can and will lead to scenarios where breaking changes happen upon running `cargo update`, *even if no changes are made in our repository* (see #743, which @Lokathor already linked). It seems awfully arbitrary to force a version bump on our end, especially given that in this scenario any pre-version-bump versions on crates.io are still going to be broken on old versions of the Rust compiler.

I'm not in theory opposed to doing this, but I don't expect it to be feasible without broader coordination in the Rust community. Until then, I have no interest in putting up with the headache that this induces.

**Comment by chrisduerr** [comment] 2019-07-29 21:28
> it's pretty much impossible to enforce a MSRV if you have dependencies that don't enforce it.

I guess binaries have it a little easier than libraries here, since lockfiles prevent dependencies from getting updated automatically downstream.

However if the library is built sufficient times and people are willing to report issues related to this, cargo is capable of fixing any issues related to this and locking down breaking dependencies temporarily is possible. To make sure this doesn't break releases it would be necessary to always specify fixed dependency versions though, which would likely cause lots of trouble downstream too with having to deal with outdated dependencies.

The reason why I personally requested a minimum supported Rust version to be specified was because winit actually broke things though. And I think that it would definitely be possible to at least track winit's minimum Rust version requirements. At the end of the day, breaking stuff because others do it isn't really a great argument, so that might at least be a good middle ground until proper support is added in cargo (which I'd expect to take at least a couple of years).

@Osspial What do you think about at least having an internal guarantee about winit not breaking stuff like accepting PRs requiring features from the latest stable right after it was released? That should be a good way to at least show that the desire for a little bit of consistency is there and might potentially inspire others to follow suite (and eventually bring around proper cargo support)?

**Comment by Lokathor** [comment] 2019-07-29 21:38
If the `winit` team is interested in moving in this direction but doesn't feel that they have the person-hours needed, I will volunteer to do it.

**Comment by chrisduerr** [comment] 2019-07-29 22:02
> If the winit team is interested in moving in this direction but doesn't feel that they have the person-hours needed, I will volunteer to do it.

I think the problem isn't necessarily person-hours, but more that it's impossible for libraries to make any guarantees for past releases since the lock file is not provided with libraries.

So any depedency of winit could get updated by a downstream user who still uses winit 0.0.1 which might have coincidentally broken the minimum supported Rust version and the only thing winit could do is yank 0.0.1 and release a new version (probably 0.0.2) which locks down the dependency to a fixed version. This would have to be done for all past releases, which is pretty much impossible to do in practice.

**Comment by Lokathor** [comment] 2019-07-29 22:09
Oh, no no, I don't think all winit versions back through time need this. Just moving to this policy going forward, starting with `winit-0.20.0` would be satisfactory.

And yes, dependencies doing a min version bump without also doing a breaking release are a problem. My suggestion there would be similar to what you said: temporarily issue a winit patch that holds that dependency back to the last version that worked, and then development going forward can bump the min version, bump the dependency to newest, and then bump the winit version.

**Comment by chrisduerr** [comment] 2019-07-29 22:14
> Oh, no no, I don't think all winit versions back through time need this. Just moving to this policy going forward, starting with winit-0.20.0 would be satisfactory.

The thing is, all *future* winit versions would have to be maintained at the same time then. It's just not feasible to yank and push new versions constantly, that'll just create a huge mess.

**Comment by Lokathor** [comment] 2019-07-29 22:21
Well, the more you do this, and the more you spread awareness of this to other crates to start playing by the same rules, the easier this process becomes. 

I do not think that you can give an absolute guarantee immediately starting in 0.20. That's definitely an unrealistic demand. However, I think that the _intent_ can be broadcast starting with 0.20, and then the situation can become more solid over time.

I don't think that versions would need to be yanked over this until quite far in the future when much more of the ecosystem is on-board with the idea. However, this is a very visible crate to help get the ball rolling with.

**Comment by francesca64** [comment] 2019-07-30 18:37
Rather than pushing the burden of this onto every library maintainer in the ecosystem, wouldn't it be better to work on pushing forward the internals discussion on Cargo features, policies, etc. that would enable making these guarantees? You have to persuade a bunch of people either way, and some people will never be convinced unless it's made official.

I've tried playing the "please yank and bump" game before, and it isn't fun. It leads to emotional friction, which leads to me feeling upset and having a bad day. I understand that your goal is to reduce that friction by making Rust version policies a *de facto* convention, but every maintainer ultimately has their own beliefs and values, and that will lead to many more threads at least as long as this one.

**Comment by Osspial** [comment] 2019-07-30 19:18
> What do you think about at least having an internal guarantee about winit not breaking stuff like accepting PRs requiring features from the latest stable right after it was released? That should be a good way to at least show that the desire for a little bit of consistency is there and might potentially inspire others to follow suite (and eventually bring around proper cargo support)?

I'm entirely okay with giving the ecosystem a few weeks to catch up to the newest stable version before accepting PRs with new features.

Beyond that, @francesca64's response reflects my views well, and I don't have much more to add at the moment. It'll be much less of headache for everyone involved to defer tackling this until the ecosystem supports it.

**Comment by Liamolucko** [comment] 2022-04-11 08:41
> I'm extremely wary about doing this without official support from Cargo (such as with [rust-lang/rfcs#2495](https://github.com/rust-lang/rfcs/pull/2495)), since it's pretty much impossible to enforce a MSRV if you have dependencies that don't enforce it.

`rust-version` in Cargo.toml was stabilised in Rust 1.56, so that's now an option.

**Closed** 2022-07-29 11:39 UTC
Labels: status: needs discussion, type: meta

**Comment by ajtribick** [comment] 2022-08-27 15:47
Looks like the MSRV imposed by dependencies is now 1.59, due to the MSRV of `time` (imported via `simple_logger`) changing in version 0.3.14 (i.e. they consider it a non-breaking change).

**Comment by Lokathor** [comment] 2022-08-27 15:49
a dev-dependency "mostly doesn't count". You can still use the lib.

**Comment by rib** [comment] 2022-08-31 23:00
Out of curiosity was there a specific reason for picking 1.57.0 as the MSRV? At the outset of this issue @goddessfreya had suggested supporting the last three stable releases which would be 1.63, 1.62 and 1.61 - is there a particular need to go back further than that?

Since I was looking at updating the Android backend to use the `android-activity` crate I've just had to remove any use of formatted strings like `info!("This is the value {foo}")` where `foo` is a variable in the scope of that line - since that wasn't introduced until 1.58. Personally I've come to use that formatting sugar a lot and was a bit disappointed to have to revert to passing explicit arguments.

Another related issue I hit with trying to update the CI for `android-activity` to also ensure it builds with `1.57.0` was realizing that `cargo ndk` doesn't build with `1.57`. So this means I now also need to upstream patches for `cargo ndk` to build `1.57` and wait for a corresponding release.

Of course there will always be _something_ you miss out on with any MSRV policy but I figured I'd check in case it was fairly arbitrary and maybe the MSRV can be moved forwards to 1.58.0?

**Comment by Lokathor** [comment] 2022-08-31 23:20
This came up in the libc MSRV discussion, and the short story is that six months to a year of lag time is needed for most of the moderate paced Linux distros (eg: Fedora, not Debian). We don't need to get there instantly, but we need to try and get there over time if we want people's winit based programs to be accepted into linux repositories without the Linux distros shipping some ancient version of the program and all it's deps.

It's not always easy, but if it's a small thing like formatting args and not an absolute requirement, then we should make an effort to slow down our msrv bumps when we can.

**Comment by chrisduerr** [comment] 2022-08-31 23:32
Yeah I think a good rule of thumb is usually to look at what Ubuntu stable is shipping. If your application can't be built on Ubuntu because its Rust version is too old, you'll probably miss out on a big portion of Linux users right there. So I'd always recommend trying to at least cover Ubuntu stable, if not Ubuntu LTS.

**Comment by rib** [comment] 2022-08-31 23:47
Thanks for the extra context. right, I had feeling it might be related to Linux distro release cycles. 

I wonder if the MSRV could somehow just be enforced for Linux since I'm not sure the same pressing need to support older compilers exists for other platforms?

The case I've hit, with needing to now update `cargo ndk` feels somewhat awkward since I now looking to upstream a patch that I'm essentially going to be justifying in terms wanting to support Winit's requirements - that mainly come from Linux distros, which should essentially be irrelevant for `cargo ndk`.

The patch for cargo ndk is trivial, and hopefully it will be possible to upstream and get a new release but the previous code was notably neater.

**Comment by Lokathor** [comment] 2022-08-31 23:53
It's probably reasonable if more niche targets like Android an iOS, which have their own special workflow, don't hold to the same standard.

You could open a new issue for that idea, because having a discussion in a closed issue is a good way to not have many eyes see it.

**Comment by madsmtm** [comment] 2022-08-31 23:54
Relatedly, can someone help me to somewhere that I can check which version of rustc "Ubuntu Stable" ships with?

**Comment by Lokathor** [comment] 2022-09-01 00:01
https://packages.ubuntu.com/jammy/rustc is one link, and if you click along the top like "bionic" or "kenetic" you can see what each LTS version uses. Looks like 1.59 (so we could reasonably 

Fedora goes back as far as 1.55: https://packages.fedoraproject.org/pkgs/rust/rust/, but then also jumps to 1.59

So probably, "soon enough" we could bring winit up to a 1.59 baseline

Which... *double checks* [is about the 6 month window](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1590-2022-02-24) that was proposed in the libc discussion.

**Comment by chrisduerr** [comment] 2022-09-01 01:25
Yeah generally sticking to the Ubuntu rule of thumb works out pretty well and covers Fedora too. And honestly I really don't think it's too much to ask to support compilers that aren't even half a year old yet. In most scenarios the changes are just small stylistic stuff, which aren't worth breaking compatibility for.

I think the bigger issue is usually just with dependencies, considering a lot of people simple don't care. But I'd argue that's just more reason to care and encourage others to do the same.

**Comment by rib** [comment] 2022-09-01 11:14
6 months as a threshold sounds a bit more reasonable, though (just in my personal opinion) I suppose even that seems overly conservative for Winit (especially for non-Linux platforms). 6 months would suggest [setting the initial minimum version to 1.60](https://github.com/rust-windowing/winit/pull/2453) I think (guessing the next Winit release will likely be > 1 month from now. This initial threshold of 1.57 will be closer to one year (10 months now, likely 11+ months by the time of the next release).
