### ISSUE TITLE
When one MouseInput button is pressed, it blocks the others (web / wasm)

### ISSUE THREAD

**Issue by cybersoulK** [rust-windowing/winit#2475] opened 2022-09-07 01:40 UTC
I dig in the code, and i narrowed it down to the use of a "pointer" instead of a "mouse"
When the left click is pressed (fine), and then right click is pressed (missing event), and left is released (missing event), the right release will never be called again

2 downsides
- it blocks the other buttons (including wheel)
- release events will never be called again

so for games it has huge impact, the action that was triggered by the mouse input can get "stuck" (because of no release event), and it does block an action from occurring entirely

Leaving the developer very confused (like me for hours xd)

**Comment by JAD3N** [comment] 2023-03-12 01:27
A hacky workaround you can use is to remove `PointerEvent` from window if touch/pen events aren't important to you.

**Comment by daxpedda** [comment] 2023-06-02 10:21
Duplicate of https://github.com/rust-windowing/winit/issues/2455.

**Closed by daxpedda** 2023-06-02 10:21 UTC
Labels: B - bug, DS - wasm
