### ISSUE TITLE
Winit creating invisible Windows on Windows

### ISSUE THREAD

**Issue by chrisduerr** [rust-windowing/winit#1265] opened 2019-11-08 05:39 UTC
It seems like there's an issue where winit is spawning invisible windows on Windows after some period of time. They seem to come from the `Winit Thread Event Target`. It seems like in the worst case this can actually lead to the process getting killed as a result of it.

A crash seems to cause the following error, however since this is likely a result, not the cause, I'd treat it with some caution.

```
panicked at 'PostMessage failed; is the messages queue full?', C:\Users\travis.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.19.1\src\platform\windows\events_loop.rs:302:13
```

This has been reported to Alacritty in https://github.com/jwilm/alacritty/issues/2656, however it has not been confirmed with the winit rework.

@leandrosansilva if you could try the latest Alacritty master and report back here if that also is broken, that would be very helpful.

**Comment by Osspial** [comment] 2019-11-21 01:07
This is by design. On Windows, a window is the base unit for dispatching and receiving messages in the event loop, and Winit creates a window to manage that upon initialization of the event loop. Having the message window show up in the taskbar *sounds* like a Windows bug, but I'm not 100% sure on that right now.

**Comment by chrisduerr** [comment] 2019-11-21 16:19
Are you saying both the window showing up at all and the crash should be fixed with the latest winit master?

**Comment by Osspial** [comment] 2019-11-26 22:17
@chrisduerr I don't know. From what you said, it sounded like that may be the case, but there needs to be some testing done to verify that.

**Comment by chrisduerr** [comment] 2019-11-26 22:20
I've asked the author of the original issue to verify, I'll report back on the status of that.

**Comment by chris-morgan** [comment] 2019-11-26 23:22
I haven’t been able to reproduce this issue in Alacritty within a few minutes. I suspect the new winit event loop may have incidentally fixed it, or possibly a Windows bug fix.

**Comment by Osspial** [comment] 2019-11-26 23:43
@chrisduerr out of curiosity, when is Alacritty with Winit 0.20 going to get published as an official release? Alacritty is our biggest (or at least, most bug-reporting) source of users, and it would be nice to bring the majority of them up-to-date with our latest code.

**Comment by chrisduerr** [comment] 2019-11-26 23:54
We've released a new version on monday, building against the (then) latest winit master with a vendored glutin.

**Comment by chris-morgan** [comment] 2019-12-17 05:27
Alas, I just reproduced the issue again. 🙁

**Comment by Osspial** [comment] 2021-07-09 18:37
I'm able to reproduce this issue fairly reliably when I use Alacritty for an extended period of time, so I've patched some logging into the Alacritty instance running on my system to hopefully get to the bottom of this.

**Comment by chris-morgan** [comment] 2021-07-09 22:38
Something I noticed late last year: the phantom window shows up in Zoom’s screen sharing window selection. This should help with trying it with the glutin examples and with bare winit.

(I was going to delve further at the time but got occupied with other things, and now I’m on a new laptop and using Linux instead of Windows.)

**Comment by Osspial** [comment] 2021-07-10 02:38
That's actually really helpful - thank you for notifying me of that!

I've added `WS_EX_TOOLWINDOW` to the event loop window and it no longer shows up in Zoom's window list, and doing so doesn't seem to have any adverse side effects, so I'm pretty sure that should function as a permanent fix. I'm gonna test it for another day or so just to verify that the issue doesn't crop up again, but if it doesn't I'll go ahead and submit that as a PR and close this issue.

**Closed** 2021-08-11 18:02 UTC
Labels: type: bug, platform: Windows, status: needs investigation
