### ISSUE TITLE
Return Err instead of panicking when EventLoopBuilder::build() fails

### ISSUE THREAD

**Issue by unlimitedbacon** [rust-windowing/winit#2511] opened 2022-10-04 06:42 UTC
I have a Linux program which silently renders images of 3D models.

I would like this program to use hardware accelerated rendering if possible (through X11 or Wayland), and fall back to OSMesa software rendering if X11 or Wayland are not available. In order to do this, my program first tries to create an EventLoop (required by Glutin for headless or surfaceless contexts) and if this fails it falls back to creating an osmesa context (no EventLoop required).

Right now I have to catch the panic if EventLoopBuilder::build() fails. Would it be possible for this function to return a Result instead, so that I can handle the failure gracefully?

[Relevant part of my code](https://github.com/unlimitedbacon/stl-thumb/blob/dec70d8d8cfbb6c635ecbd8c1f3d3959ea42f5e8/src/lib.rs#L110)

**Comment by kchibisov** [comment] 2022-10-04 07:38
Duplicate of #500.

**Closed by kchibisov** 2022-10-04 07:38 UTC
