### ISSUE TITLE
 A way to disable key repeats

### ISSUE THREAD

**Issue by ryanisaacg** [rust-windowing/winit#310] opened 2017-10-07 17:02 UTC
At least on Windows, key events seem to respond with a delay (especially when a key is being mashed) due to key repeat handling. Is there any way to disable this?

(Originally [I asked in glutin but was referred here](https://github.com/tomaka/glutin/issues/943))

**Comment by vberger** [comment] 2017-10-07 17:07
For the record, the usecase of disabling key repeats is also of interest for [smithay](https//github.com/Smithay/smithay), otherwise we would need to filter-out repeated events...

**Comment by ryanisaacg** [comment] 2017-10-07 20:51
@vberger I think you're missing the ":" in the "https://" of your link

**Comment by vberger** [comment] 2017-10-08 09:54
Indeed, I've corrected it. 😅

**Comment by francesca64** [comment] 2018-04-22 19:04
We actually can't implement this on X11 without resorting to heuristics, though AFAIK it's straightforward to implement on Windows.

**Comment by francesca64** [comment] 2018-05-15 12:59
It's also easy to implement on macOS. Since there's a precedent for how to handle this on X11, we might as well go for it (though I don't consider it a priority at present). 

What's the ideal here? Adding an `is_repeat` field to `KeyboardInput`? Or it being configurable to completely strip out repeats? Both?

**Comment by fschutt** [comment] 2018-09-06 16:58
On windows, key repetition is currently way too fast, I'm not sure what's up with that, if it's a bug or not - is there any way to disable key repetition in winit? It's just because if I type "Hello World", I get "HHeeello WWWorrrrld" because the delay for key repetition is extremely low for some reason.

**Comment by francesca64** [comment] 2018-09-11 04:10
@fschutt I'm not able to reproduce that on Windows 10, though making it possible to filter key repeats would be easy on all platforms other than X11. I'm curious about why that's happening at all, though.

**Comment by zpgaal** [comment] 2019-03-07 12:45
I'd suggest (without knowing the internals of winit) to add a new ElementState: Repeat.
It can be discarded in the event loop if required.

**Comment by Osspial** [comment] 2019-04-24 19:43
Closing in favor of #753 and #812

**Closed by Osspial** 2019-04-24 19:43 UTC
Labels: difficulty: hard, priority: normal, status: help wanted, type: api

**Comment by Kittenlover229** [comment] 2023-06-28 17:35
It seems like necroposting, but I've spend a decent amount researching relevant issues with no avail. Perhaps a hacky solution could be outlined *at least as a temporary fix*? It seems like the proposed bodge solution from GLFW doesn't exactly work, since winit doesn't provide the event timestamps.

**Comment by kchibisov** [comment] 2023-06-28 17:38
`KeyEvent` has `is_repeat` field, so simply ignore repeats.

**Comment by Kittenlover229** [comment] 2023-06-29 03:04
Am I missing any feature flags? Currently looking at the latest 0.28.6 version and not seeing anything called `KeyEvent` or similar. There is [`KeyboardInput`](https://docs.rs/winit/0.28.6/winit/event/enum.WindowEvent.html#variant.KeyboardInput), but it doesn't seem to have the `is_repeat` field.

**Comment by kchibisov** [comment] 2023-06-29 09:40
Yeah, you need winit from master.
