### ISSUE TITLE
On Windows, the background is initially white and doesn't properly redraw

### ISSUE THREAD

**Issue by iulianR** [rust-windowing/winit#1290] opened 2019-11-26 20:59 UTC
White
![image](https://user-images.githubusercontent.com/6775259/69672057-fbe2a300-109f-11ea-84ee-92a01599b9f7.png)

I'm trying to run the examples from the latest master and I see something like this with all of them. The part of the window that is initially displayed, always remains white. If I resize, it looks like it properly renders as black. Even the transparent example is initially white and only after I resize, the new parts of the window are transparent. Looks similar to this issue #1012 .

Let me know if I can provide more info, thanks!

**Comment by Osspial** [comment] 2019-11-26 23:04
This is the expected behavior. Winit doesn't actually do anything to draw onto the window; instead, that's handled by higher-level libraries like `gfx-hal`. What you're seeing there is Windows' default behavior when the OS asks the application to redraw, but the application does nothing.

I'm closing this since it's not an issue with Winit, but please let me know if you've got any more questions!

**Closed by Osspial** 2019-11-26 23:04 UTC

**Comment by AuracleTech** [comment] 2023-05-03 23:02
Any alternatives?

**Comment by kchibisov** [comment] 2023-05-03 23:59
>Any alternatives?

Draw? It's not a problem for a real application because it draws. You have plenty of libraries,ui-toolkits, etc to do so. winit won't ever draw on its own.
