### ISSUE TITLE
Triggering the system return key cannot exit correctly.

### ISSUE THREAD

**Issue by paulzhang5511** [rust-windowing/winit#3948] opened 2024-10-13 02:36 UTC
### Description

When the system return key is triggered and `event_loop.exit()`; is called to exit the Android NativeActivity, an error occurs when entering the Android NativeActivity again: **RecreationAttempt**.

<img width="825" alt="image" src="https://github.com/user-attachments/assets/de02c187-1c87-4f37-b90c-eca7a1ef724a">

1. Listen for the system return key.

```rust
 WindowEvent::KeyboardInput {
                event,
                is_synthetic: false,
                ..
            } => {
                // Dispatch actions only on press.
                if event.state.is_pressed() {

                    if let Key::Named(ch) = event.logical_key.as_ref() {
                        event_loop.exit();
                    }
                }
            }
```
2. Exit the event loop and close the page.

```rust
  event_loop.exit();
```

3. Code Example

https://github.com/paulzhang5511/HelloAndroidEgui/blob/android-winit/rustlib/src/lib.rs

### Device and Android version

Pixel8 running in android14

### Winit version

0.30.5

**Comment by paulzhang5511** [comment] 2024-10-13 14:14
A solution has been found.

https://github.com/SnowyCoder/winit-fix-android/commit/e4fa39d8182e3578b63a366727f17fceae4644e0#diff-f5a20b394a5ba72e0e625bac291ac8e2fa04a59b2801dae39b277499d14729fd

```rust
    #[cfg(any(wasm_platform, android_platform))]
    pub fn allow_event_loop_recreation() {
        EVENT_LOOP_CREATED.store(false, Ordering::Relaxed);
    }
```

```rust
impl<T> Drop for EventLoop<T> {
    fn drop(&mut self) {
        crate::event_loop::EventLoopBuilder::<()>::allow_event_loop_recreation();
    }
}
```

**Comment by kchibisov** [comment] 2024-10-13 18:06
How does it end up re-creating it though? I'd assume that you're not destroying the loop and then creating a new one yourself?

**Comment by daxpedda** [comment] 2024-10-13 18:48
> I'd assume that you're not destroying the loop and then creating a new one yourself?

That's exactly what I understood is happening here, in which case everything works as expected.

If this is the problem, we might indeed want to consider allowing recreation of the event loop on Android.

**Comment by paulzhang5511** [comment] 2024-10-16 01:14
Hope this issue can be fixed as soon as possible. Not allowing the recreation of event loops is unfriendly to Android development. Thank you.

**Comment by paulzhang5511** [comment] 2024-10-16 01:15
https://github.com/rust-windowing/winit/issues/3325

**Comment by kchibisov** [comment] 2024-10-16 01:28
What's the reason to exit the loop in the first place on android and not just _wait_? I'd assume there's no other way to minimize things for you?

**Comment by paulzhang5511** [comment] 2024-10-16 02:21
After exiting the loop, close the page "winit page". Click "Go winit page" again to enter "winit page". Do not recreate the event loop again, otherwise it will cause the program to crash.

**Comment by MarijnS95** [comment] 2024-10-16 08:13
This issue seems to have little to do with the "system return key" and all with opening new `Activity`s inside the same `Application`. That problematic behaviour, which was inadvertently retained even in the probably close to ~4th refactor of the Android backend, is fully described in https://github.com/rust-windowing/winit/issues/3325#issuecomment-1879742860.

How about closing this as duplicate of #3325?

**Closed** 2024-10-16 09:27 UTC
Labels: B - bug, DS - android
